// Traducción al inglés. Clave: el texto original en español, tal cual aparece
// en el código o en el HTML. Ver js/i18n.js.
const I18N_EN = {
  // ---- Marco de la app y navegación ----
  'Mi journal · Journal Trading': 'My journal · Journal Trading',
  'Journal Trading': 'Journal Trading',
  'Inicio': 'Home',
  'Trade': 'Trade',
  'Stats': 'Stats',
  'Estadísticas': 'Statistics',
  'Calendario': 'Calendar',
  'Historial': 'History',
  'Revisión': 'Review',
  'Revisión semanal': 'Weekly review',
  'Ajustes': 'Settings',
  'Cerrar sesión': 'Log out',
  'Salir': 'Log out',
  'No soy yo · Cerrar sesión': 'Not me · Log out',
  'Cerrar': 'Close',
  'Cuenta que estás viendo': 'Account you are viewing',
  'Cambiar a modo claro': 'Switch to light mode',
  'Cambiar a modo oscuro': 'Switch to dark mode',
  'Guardado': 'Saved',

  // ---- Plan y prueba ----
  'Pro · anual': 'Pro · yearly',
  'Pro · mensual': 'Pro · monthly',
  'Prueba gratis': 'Free trial',
  'Prueba terminada': 'Trial ended',
  'queda 1 día': '1 day left',
  'quedan {n} días': '{n} days left',
  'por año · {price}/mes': 'per year · {price}/month',
  'Tu prueba gratis terminó': 'Your free trial has ended',
  'Pasate a Pro': 'Upgrade to Pro',
  'Pasar a Pro': 'Upgrade to Pro',
  'Pasate a Pro para seguir registrando trades. Tus datos siguen guardados.': 'Upgrade to Pro to keep logging trades. Your data is still saved.',
  'Seguí entrenando tu disciplina sin límite de tiempo.': 'Keep training your discipline with no time limit.',
  '¡Listo, ya sos Pro!': "Done, you're Pro now!",
  'Seguí registrando tus trades sin límite.': 'Keep logging your trades with no limits.',
  'Mensual': 'Monthly',
  'por mes': 'per month',
  'Anual': 'Yearly',
  '20% de descuento pagando anual.': '20% off when you pay yearly.',
  'Ahora no': 'Not now',
  'Descargar mis datos': 'Download my data',
  'Tu plan': 'Your plan',
  'anual': 'yearly',
  'mensual': 'monthly',
  '/año': '/year',
  '/mes': '/month',
  'Miembro desde {since}.': 'Member since {since}.',
  'Te queda 1 día de prueba.': 'You have 1 trial day left.',
  'Te quedan {n} días de prueba.': 'You have {n} trial days left.',
  'Tu prueba terminó.': 'Your trial has ended.',

  // ---- Inicio (texto fijo) ----
  'Revisar semana': 'Review week',
  'Ver stats': 'See stats',
  'Tu día de hoy': 'Your day today',
  'Meta del mes': 'Monthly goal',
  'Cambiar meta →': 'Change goal →',
  'Cuánto margen te queda según las reglas de tu prop firm.': 'How much room you have left under your prop firm rules.',
  'Tu semana': 'Your week',
  'Calendario →': 'Calendar →',
  'Últimos trades': 'Latest trades',
  'Historial →': 'History →',
  'Lo que dicen tus datos': 'What your data says',
  'Ver todos →': 'See all →',
  'Logros': 'Achievements',

  // ---- Registrar trade ----
  'Registrar trade': 'Log trade',
  'Editar trade': 'Edit trade',
  'Agregar trade': 'Add trade',
  'Guardar cambios': 'Save changes',
  'Cancelar edición': 'Cancel editing',
  'Paso 1 de 4': 'Step 1 of 4',
  'Paso 2 de 4': 'Step 2 of 4',
  'Paso 3 de 4': 'Step 3 of 4',
  'Paso 4 de 4': 'Step 4 of 4',
  '{n} de 4 secciones completas': '{n} of 4 sections complete',
  'Tu Trading Plan': 'Your Trading Plan',
  'Tocá cada regla que cumpliste': 'Tap each rule you followed',
  'Todavía no armaste tu Trading Plan. Cargá las reglas que tiene que cumplir cada trade y acá vas a poder tildarlas.': "You haven't built your Trading Plan yet. Add the rules every trade must follow and you'll be able to check them off here.",
  'Armar mi Trading Plan': 'Build my Trading Plan',
  'Cumpliste <b>{done}/{total}</b> reglas': 'You followed <b>{done}/{total}</b> rules',
  'Dentro del plan': 'Within plan',
  'Fuera del plan': 'Off plan',
  'Sin marcar': 'Not checked',
  'El trade': 'The trade',
  'Qué operaste y cómo salió': 'What you traded and how it went',
  'Cuenta': 'Account',
  'Resultado': 'Result',
  'Ganador': 'Winner',
  'Perdedor': 'Loser',
  'Break even': 'Break even',
  'TP': 'TP',
  'SL': 'SL',
  'BE': 'BE',
  'Dirección': 'Direction',
  'Long': 'Long',
  'Short': 'Short',
  'Activo': 'Asset',
  'Ej. NQ, EURUSD': 'E.g. NQ, EURUSD',
  'Fecha y hora de entrada': 'Entry date and time',
  'hora de Nueva York': 'New York time',
  'tu hora local': 'your local time',
  'Sesión: {s}': 'Session: {s}',
  'Cuenta para el día {d}': 'Counts for {d}',
  '{time} tu hora': '{time} your time',
  'Setup': 'Setup',
  'Ej. Sweep + IFVG': 'E.g. Sweep + IFVG',
  'Riesgo (%)': 'Risk (%)',
  'Ej. 0.5': 'E.g. 0.5',
  'R:R planeado': 'Planned R:R',
  'Ej. 2 (para 1:2)': 'E.g. 2 (for 1:2)',
  'Resultado real (%)': 'Actual result (%)',
  'Ej. 1.2 o -0.5': 'E.g. 1.2 or -0.5',
  'R real': 'Actual R',
  'R real: {r}': 'Actual R: {r}',
  'Duración (minutos)': 'Duration (minutes)',
  'Ej. 12': 'E.g. 12',
  'Tu cabeza': 'Your mindset',
  'Cómo estabas cuando entraste': 'How you felt when you entered',
  '¿Cómo te sentías al entrar?': 'How did you feel when you entered?',
  'Estados que ayudan': 'Helpful states',
  'Estados de riesgo': 'Risky states',
  'Tranquilo': 'Calm',
  'Confiado': 'Confident',
  'Ansioso': 'Anxious',
  'Revancha': 'Revenge',
  'Aburrido': 'Bored',
  'Nivel de confianza en el trade': 'Confidence in the trade',
  'Confianza 1': 'Confidence 1',
  'Confianza 2': 'Confidence 2',
  'Confianza 3': 'Confidence 3',
  'Confianza 4': 'Confidence 4',
  'Confianza 5': 'Confidence 5',
  'Nada seguro': 'Not sure at all',
  'Poco seguro': 'Slightly sure',
  'Neutral': 'Neutral',
  'Bastante seguro': 'Fairly sure',
  'Totalmente seguro': 'Completely sure',
  '¿Cometiste algún error?': 'Did you make any mistakes?',
  '(podés marcar varios)': '(you can pick several)',
  'Moví el stop': 'Moved my stop',
  'Cerré antes de tiempo': 'Closed too early',
  'Entré tarde': 'Entered late',
  'Entré sin confirmación': 'Entered without confirmation',
  'Sobreoperé': 'Overtraded',
  'Aumenté el tamaño': 'Sized up',
  'No respeté el TP': "Didn't respect my TP",
  'Notas': 'Notes',
  'Lo que querés recordar de este trade': 'What you want to remember about this trade',
  '¿Qué pasó en el desarrollo del trade?': 'What happened during the trade?',
  '(opcional)': '(optional)',
  'Ej. Esperé la confirmación, pero cerré antes por miedo a que volviera.': 'E.g. I waited for confirmation, but closed early out of fear it would reverse.',
  'Arrastrá la imagen acá o': 'Drag the image here or',
  'elegí un archivo': 'choose a file',
  'PNG o JPG · también podés pegarla con Ctrl+V': 'PNG or JPG · you can also paste it with Ctrl+V',
  'Captura del trade': 'Trade screenshot',
  'Cambiar': 'Change',
  'Quitar': 'Remove',
  'Vista previa': 'Preview',
  'Completá el formulario y el trade se arma acá.': 'Fill in the form and your trade takes shape here.',
  'Plan respetado': 'Plan followed',
  'Sí': 'Yes',
  'No': 'No',
  'Emoción': 'Emotion',
  'Errores': 'Mistakes',
  'Puntaje de disciplina': 'Discipline score',
  'Completá el formulario para ver tu puntaje.': 'Fill in the form to see your score.',
  'Trade ejecutado con disciplina.': 'Trade executed with discipline.',
  'Hay cosas para ajustar.': 'Some things to adjust.',
  'Este trade se alejó de tu plan.': 'This trade drifted from your plan.',
  'El riesgo tiene que ser un número (ej. 0.5).': 'Risk must be a number (e.g. 0.5).',
  'El riesgo tiene que ser mayor a 0 y como máximo 100%.': 'Risk must be greater than 0 and at most 100%.',
  'El R:R planeado tiene que ser un número (ej. 2).': 'Planned R:R must be a number (e.g. 2).',
  'El R:R planeado tiene que ser mayor a 0 (ej. 2 para 1:2).': 'Planned R:R must be greater than 0 (e.g. 2 for 1:2).',
  'La duración tiene que ser un número de minutos (ej. 12).': 'Duration must be a number of minutes (e.g. 12).',
  'La duración no puede ser negativa.': "Duration can't be negative.",
  'Elegí un resultado (Ganador, Perdedor o Break even) antes de registrar.': 'Pick a result (Winner, Loser or Break even) before logging.',
  'El resultado tiene que ser un número (ej. 1.2 o -0.5).': 'Result must be a number (e.g. 1.2 or -0.5).',
  'Revisá el resultado: no puede ser mayor a 100% ni menor a -100%.': "Check the result: it can't be above 100% or below -100%.",
  'Marcaste Ganador pero el resultado es negativo. Revisá el resultado o elegí Perdedor.': 'You picked Winner but the result is negative. Check the result or pick Loser.',
  'Marcaste Perdedor pero el resultado es positivo. Revisá el resultado o elegí Ganador.': 'You picked Loser but the result is positive. Check the result or pick Winner.',
  'Revisá la fecha y hora de entrada.': 'Check the entry date and time.',
  'La fecha de entrada no puede ser futura.': "The entry date can't be in the future.",
  'Ese trade ya no existe (se eliminó). No se guardaron los cambios.': 'That trade no longer exists (it was deleted). Your changes were not saved.',
  'No marcaste ninguna regla de tu Trading Plan. Si guardás así, el trade queda como "Plan roto". ¿Guardar igual?': 'You didn\'t check any rule from your Trading Plan. If you save like this, the trade is marked "Plan broken". Save anyway?',
  'No se pudo guardar el trade porque el almacenamiento del navegador está lleno. Exportá un backup y liberá espacio.': "The trade couldn't be saved because browser storage is full. Export a backup and free up space.",

  // ---- Estadísticas, historial y revisión (texto fijo) ----
  'Período': 'Period',
  'Esta semana': 'This week',
  'Este mes': 'This month',
  '3 meses': '3 months',
  'Todo': 'All',
  'Disciplina': 'Discipline',
  'Trades con tu plan respetado contra tu meta.': 'Trades that followed your plan vs. your goal.',
  'Curva de resultados': 'Equity curve',
  'Resultado real': 'Actual result',
  'Si hubieras seguido tu plan': 'If you had followed your plan',
  'Lo que te costó romperlo': 'What breaking it cost you',
  'Plan roto': 'Plan broken',
  'Plan seguido': 'Plan followed',
  'Patrones que aparecen en tus trades del período.': 'Patterns showing up in your trades for this period.',
  'Mapa de calor: cuándo rompés el plan': 'Heatmap: when you break your plan',
  'Cada celda es un día y una hora de entrada, en hora de Nueva York. Pasá el mouse para ver el detalle.': 'Each cell is an entry day and hour, in New York time. Hover to see the details.',
  'El número es la cantidad de trades': 'The number is the trade count',
  'Desglose': 'Breakdown',
  'Sesión': 'Session',
  'Plan seguido vs. plan roto': 'Plan followed vs. plan broken',
  'Lo mismo medido de los dos lados.': 'The same metrics on both sides.',
  'Qué regla cumplís más': 'Which rules you follow most',
  'Porcentaje de trades en los que tildaste cada regla.': 'Share of trades where you checked each rule.',
  'Cierre mensual': 'Monthly close',
  'Cada mes se cierra solo al terminar. Siempre muestra todo tu historial.': 'Each month closes automatically when it ends. It always shows your full history.',
  'Hoy': 'Today',
  'Mes': 'Month',
  'Año': 'Year',
  'Anterior': 'Previous',
  'Buscar por activo, setup o nota': 'Search by asset, setup or note',
  'Buscar trades': 'Search trades',
  'Ordenar': 'Sort',
  'Más recientes': 'Newest',
  'Más antiguos': 'Oldest',
  'Mejor resultado': 'Best result',
  'Peor resultado': 'Worst result',
  'Mayor riesgo': 'Highest risk',
  'Ganadores': 'Winners',
  'Perdedores': 'Losers',
  'Con errores': 'With mistakes',
  'Con captura': 'With screenshot',
  'Por completar': 'To complete',
  'Semana anterior': 'Previous week',
  'Semana siguiente': 'Next week',
  'Resultado por día': 'Result by day',
  'Trades de la semana': "This week's trades",
  'Revisión guiada': 'Guided review',
  'Cinco minutos al final de la semana para mirar cómo operaste, no solo cuánto ganaste.': 'Five minutes at the end of the week to look at how you traded, not just how much you made.',
  'Lo que hiciste bien': 'What you did well',
  '¿Qué hiciste bien esta semana?': 'What did you do well this week?',
  'Ej. Esperé la confirmación en todos los trades y respeté el horario.': 'E.g. I waited for confirmation on every trade and stuck to my hours.',
  'El error que se repitió': 'The mistake that repeated',
  '¿Qué error se repitió y por qué creés que pasó?': 'Which mistake repeated and why do you think it happened?',
  'Ej. Cerré antes de tiempo dos veces por miedo a devolver la ganancia.': 'E.g. I closed early twice out of fear of giving back profit.',
  'Qué vas a cambiar': "What you'll change",
  '¿Qué vas a hacer distinto la semana que viene?': 'What will you do differently next week?',
  '(va a ser tu compromiso)': "(it'll be your commitment)",
  'Ej. Dejar correr el trade hasta el TP salvo que se invalide el setup.': 'E.g. Let the trade run to TP unless the setup is invalidated.',
  'Del 1 al 10, ¿cómo calificás tu disciplina esta semana?': 'From 1 to 10, how would you rate your discipline this week?',
  'Guardar revisión': 'Save review',
  'Revisiones anteriores': 'Past reviews',
  'Cómo evoluciona tu nota de disciplina semana a semana.': 'How your discipline score evolves week by week.',
  '+ Registrar trade en este día': '+ Log a trade on this day',

  // ---- Ajustes ----
  'Perfil': 'Profile',
  'Cómo te ves en la app y en qué plan estás.': 'How you appear in the app and which plan you are on.',
  'Nombre': 'Name',
  'Email': 'Email',
  'Color del avatar': 'Avatar color',
  'Color por defecto': 'Default color',
  'Color {c}': 'Color {c}',
  'Idioma · Language': 'Language · Idioma',
  'Metas y riesgo': 'Goals and risk',
  'Los límites que te ponés para operar con disciplina.': 'The limits you set to trade with discipline.',
  'Meta del mes: trades con el plan respetado': 'Monthly goal: trades that followed the plan',
  'Ej. 80': 'E.g. 80',
  'Meta personalizada': 'Custom goal',
  'Todavía no registraste trades este mes. La meta es que el <b>{goal}%</b> respete tu plan.': "You haven't logged trades this month yet. The goal is for <b>{goal}%</b> to follow your plan.",
  'Este mes vas <b>{pct}%</b> ({done}/{n})': 'This month you are at <b>{pct}%</b> ({done}/{n})',
  'Vas cumpliendo la meta. Mantenela hasta fin de mes.': "You're on track. Keep it up until the end of the month.",
  'Este mes ya no se puede llegar al 100%.': "100% is no longer reachable this month.",
  'Te falta <b>1</b> trade seguido respetando el plan para llegar.': 'You need <b>1</b> more trade in a row following the plan to get there.',
  'Te faltan <b>{n}</b> trades seguidos respetando el plan para llegar.': 'You need <b>{n}</b> trades in a row following the plan to get there.',
  'Riesgo máximo por día según tu Trading Plan': 'Max risk per day according to your Trading Plan',
  'Ej. 1': 'E.g. 1',
  'Riesgo personalizado': 'Custom risk',
  'Elegí tu riesgo máximo diario para ver cuánto te queda cada día.': 'Set your max daily risk to see how much you have left each day.',
  'Riesgo tomado hoy': 'Risk taken today',
  'Límite superado': 'Limit exceeded',
  'Límite alcanzado': 'Limit reached',
  'Cerca del límite': 'Close to the limit',
  'Dentro del límite': 'Within the limit',
  'Arriesgaste {used}% y tu máximo es {max}%. Hoy rompiste tu risk management.': 'You risked {used}% and your max is {max}%. You broke your risk management today.',
  'Ya usaste todo tu riesgo de hoy. Lo que sigue es fuera de plan.': "You've used all your risk for today. Anything else is off plan.",
  'Te quedan {n}% de riesgo para hoy.': 'You have {n}% risk left for today.',
  'Horarios': 'Time',
  'Las estadísticas, el calendario y las sesiones se calculan siempre en hora de Nueva York, la referencia del trading.': 'Statistics, the calendar and sessions are always calculated in New York time, the trading standard.',
  'Mostrar y cargar las horas en': 'Show and enter times in',
  'Hora de Nueva York': 'New York time',
  'Mi hora local': 'My local time',
  'Tu hora local coincide con la de Nueva York.': 'Your local time matches New York time.',
  'Ahora son las {ny} en Nueva York y las {local} en tu zona ({zone}).': "It's {ny} in New York and {local} in your time zone ({zone}).",
  'El día de trading termina a las': 'The trading day ends at',
  'Medianoche NY': 'NY midnight',
  '17:00 NY (forex y futuros)': '5:00 PM NY (forex and futures)',
  'Lo que operes desde las 17:00 de NY cuenta para el día siguiente, como el cierre de forex y futuros.': 'Anything you trade from 5:00 PM NY counts for the next day, like the forex and futures close.',
  'Cada día va de 00:00 a 23:59 en hora de Nueva York.': 'Each day runs from 00:00 to 23:59 New York time.',
  'Sesiones y killzones': 'Sessions and killzones',
  '(hora de Nueva York)': '(New York time)',
  'Nombre de la sesión': 'Session name',
  'Empieza (hora NY)': 'Starts (NY time)',
  'Termina (hora NY)': 'Ends (NY time)',
  'a': 'to',
  '{from} a {to} en tu hora': '{from} to {to} your time',
  'Eliminar sesión': 'Delete session',
  'Sin sesiones: todos los trades quedan "Fuera de sesión".': 'No sessions: every trade is "Outside session".',
  'Poné un nombre a la sesión.': 'Give the session a name.',
  'Completá la hora de inicio y de fin.': 'Fill in the start and end time.',
  'La sesión tiene que empezar y terminar a horas distintas.': 'The session must start and end at different times.',
  'Podés tener hasta 12 sesiones.': 'You can have up to 12 sessions.',
  'Nueva sesión': 'New session',
  '+ Agregar sesión': '+ Add session',
  '+ Killzones ICT': '+ ICT killzones',
  'Volver a las de siempre': 'Reset to defaults',
  '¿Volver a las sesiones de siempre (Asia, Londres y Nueva York)? Se borran las que agregaste.': 'Reset to the default sessions (Asia, London and New York)? The ones you added will be deleted.',
  'Cada trade toma la sesión de su hora de entrada. Si dos se superponen, cuenta la más corta (la killzone gana sobre la sesión entera). Los cambios se aplican también a los trades que ya cargaste.': 'Each trade takes the session of its entry time. If two overlap, the shorter one wins (a killzone wins over the full session). Changes also apply to trades you already logged.',
  'Asia': 'Asia',
  'Londres': 'London',
  'Nueva York': 'New York',
  'Fuera de sesión': 'Outside session',
  'Datos y backup': 'Data and backup',
  'Por ahora tus datos se guardan solo en este navegador. Exportá un backup para no perderlos o pasarlos a otro dispositivo.': 'For now your data is stored only in this browser. Export a backup so you don\'t lose it or to move it to another device.',
  'Exportar backup': 'Export backup',
  'Descargá un archivo con todos tus datos.': 'Download a file with all your data.',
  'Importar backup': 'Import backup',
  'Reemplazá tus datos por los de un archivo.': 'Replace your data with the data in a file.',
  'Importar trades (CSV)': 'Import trades (CSV)',
  'Traé tu historial desde cualquier broker o plataforma. Se suman a los que ya tenés.': 'Bring in your history from any broker or platform. They are added to the ones you already have.',
  'Esto reemplaza todos los datos actuales por los del backup ({n} trades{extra}). ¿Continuar?': 'This replaces all your current data with the backup ({n} trades{extra}). Continue?',
  '; {n} registros dañados se van a descartar': '; {n} damaged records will be discarded',
  'No se pudo leer el archivo.': "The file couldn't be read.",
  'No se pudieron leer tus datos guardados (el archivo está dañado). Se guardó una copia aparte; si tenés un backup, importalo desde Ajustes.': "Your saved data couldn't be read (the file is damaged). A copy was saved separately; if you have a backup, import it from Settings.",
  'No se pudo guardar: el almacenamiento del navegador está lleno. Exportá un backup y borrá trades viejos o imágenes.': "Couldn't save: browser storage is full. Export a backup and delete old trades or images.",
  'No se pudo guardar en el navegador. Exportá un backup desde Ajustes para no perder datos.': "Couldn't save in the browser. Export a backup from Settings so you don't lose data.",
  'Zona peligrosa': 'Danger zone',
  'Borra todos tus trades, rachas y meses cerrados. Tu Trading Plan y tus ajustes se mantienen.': 'Deletes all your trades, streaks and closed months. Your Trading Plan and settings are kept.',
  'Borrar todo el historial': 'Delete all history',
  '¿Seguro? Se borran todos tus trades y no se puede deshacer.': 'Are you sure? All your trades will be deleted and this cannot be undone.',
  'Sí, borrar todo': 'Yes, delete everything',
  'Las reglas que tiene que cumplir cada trade, en el orden en que las revisás.': 'The rules every trade must follow, in the order you check them.',
  'Escribí una nueva regla': 'Write a new rule',
  'Aclaración opcional (ej. 9:30 a 11:00 NY)': 'Optional note (e.g. 9:30 to 11:00 NY)',
  'Agregar': 'Add',
  '+ Agregar aclaración': '+ Add note',
  'Regla': 'Rule',
  'Aclaración (opcional)': 'Note (optional)',
  'Aclaración': 'Note',
  'Subir': 'Move up',
  'Bajar': 'Move down',
  'Editar': 'Edit',
  'Editar regla': 'Edit rule',
  'Eliminar regla': 'Delete rule',
  'Tu Trading Plan está vacío. Agregá la primera regla abajo.': 'Your Trading Plan is empty. Add your first rule below.',
  '¿Eliminar la regla "{rule}" de tu Trading Plan? Los trades que ya cargaste la siguen mostrando como estaba.': 'Delete the rule "{rule}" from your Trading Plan? Trades you already logged keep showing it as it was.',
  '{n} regla': '{n} rule',
  '{n} reglas': '{n} rules',
  'Guardar': 'Save',
  'Cancelar': 'Cancel',
  'Eliminar': 'Delete',
  'Eliminar…': 'Delete…',

  // ---- Cuentas ----
  'Cuentas': 'Accounts',
  'Tu cuenta personal, challenges y cuentas fondeadas, cada una con sus reglas.': 'Your personal account, challenges and funded accounts, each with its own rules.',
  '+ Agregar cuenta': '+ Add account',
  'Mi cuenta': 'My account',
  'Todas las cuentas': 'All accounts',
  '{n} cuenta': '{n} account',
  '{n} cuentas': '{n} accounts',
  '{n} trade': '{n} trade',
  '{n} trades': '{n} trades',
  'Personal': 'Personal',
  'Challenge': 'Challenge',
  'Fondeada': 'Funded',
  'Activa': 'Active',
  'Aprobada': 'Passed',
  'Quemada': 'Failed',
  'Archivada': 'Archived',
  'Cuenta de fondeo': 'Funded account',
  'Cuentas de fondeo': 'Funded accounts',
  'Crear fondeada': 'Create funded',
  '{name} fondeada': '{name} funded',
  'Editar cuenta': 'Edit account',
  'Nueva cuenta': 'New account',
  'Tipo': 'Type',
  'Tu propia cuenta, sin reglas de una prop firm.': 'Your own account, without prop firm rules.',
  'La evaluación de una prop firm: tenés que llegar al objetivo sin romper las reglas.': "A prop firm evaluation: you have to hit the target without breaking the rules.",
  'Cuenta ya fondeada: se cuidan los drawdowns, sin objetivo.': 'Already funded: protect the drawdowns, no target.',
  'Ej. Challenge 50K fase 1': 'E.g. 50K Challenge phase 1',
  'Ej. Mi cuenta': 'E.g. My account',
  'Prop firm': 'Prop firm',
  'Ej. tu prop firm': 'E.g. your prop firm',
  'Tamaño en USD (opcional)': 'Size in USD (optional)',
  'Ej. {v}': 'E.g. {v}',
  'Reglas': 'Rules',
  'Drawdown diario': 'Daily drawdown',
  'Drawdown máximo': 'Max drawdown',
  'Tipo de drawdown máximo': 'Max drawdown type',
  'Estático': 'Static',
  'Trailing': 'Trailing',
  'Profit target': 'Profit target',
  'Días mínimos (opcional)': 'Minimum days (optional)',
  'Consistencia': 'Consistency',
  'Consistencia (opcional)': 'Consistency (optional)',
  'El piso deja de subir cuando llega al balance inicial (mi firma congela el trailing)': 'The floor stops rising once it reaches the starting balance (my firm locks the trailing)',
  'La consistencia limita cuánto puede pesar tu mejor día sobre la ganancia total (ej. 30%: ningún día puede ser más del 30% del total).': 'Consistency limits how much your best day can weigh on total profit (e.g. 30%: no day can be more than 30% of the total).',
  'Estado': 'Status',
  'Poné un nombre para reconocer la cuenta.': 'Give the account a name you will recognize.',
  'El tamaño tiene que ser un número (ej. 50000).': 'Size must be a number (e.g. 50000).',
  'drawdown diario': 'daily drawdown',
  'drawdown máximo': 'max drawdown',
  'el drawdown diario': 'the daily drawdown',
  'el drawdown máximo': 'the max drawdown',
  'profit target': 'profit target',
  'consistencia': 'consistency',
  'Revisá el {rule}: tiene que ser un número entre 0 y 100.': 'Check the {rule}: it must be a number between 0 and 100.',
  'Los días mínimos tienen que ser un número entero (ej. 4).': 'Minimum days must be a whole number (e.g. 4).',
  'No se pudo guardar.': "Couldn't save.",
  '"{acc}" tiene 1 trade. Si la eliminás, pasa a "{other}". Si querés conservarlo aparte, mejor archivala (Estado → Archivada). ¿Eliminar igual?': '"{acc}" has 1 trade. If you delete it, it moves to "{other}". To keep it separate, archive the account instead (Status → Archived). Delete anyway?',
  '"{acc}" tiene {n} trades. Si la eliminás, pasan a "{other}". Si querés conservarlos aparte, mejor archivala (Estado → Archivada). ¿Eliminar igual?': '"{acc}" has {n} trades. If you delete it, they move to "{other}". To keep them separate, archive the account instead (Status → Archived). Delete anyway?',
  '{acc}: ya no te queda margen hasta {which}. Hoy no operes esta cuenta.': "{acc}: you have no room left before {which}. Don't trade this account today.",
  'Cuidado: arriesgás {risk}% y en {acc} te quedan {left}% hasta {which}.': 'Careful: you are risking {risk}% and {acc} only has {left}% left before {which}.',
  '{acc}: te quedan {left} hasta {which}.': '{acc}: {left} left before {which}.',
  'Regla rota': 'Rule broken',
  'Rompiste el {rule} el {date}. Si tu prop firm la dio por perdida, marcala como quemada.': 'You broke the {rule} on {date}. If your prop firm failed the account, mark it as failed.',
  'Objetivo cumplido': 'Target reached',
  'Cumpliste todas las reglas del challenge. Cuando tu firma lo confirme, marcala como aprobada.': 'You met every challenge rule. Once your firm confirms it, mark it as passed.',
  'Falta una regla': 'One rule missing',
  'Llegaste al objetivo pero te faltan días operados.': 'You hit the target but still need more trading days.',
  'Llegaste al objetivo pero tu mejor día pesa demasiado (regla de consistencia).': 'You hit the target but your best day weighs too much (consistency rule).',
  'En curso': 'In progress',
  'te quedan {left}': '{left} left',
  'límite alcanzado': 'limit reached',
  'Hoy: {pnl}': 'Today: {pnl}',
  '(trailing, se congela en el inicial)': '(trailing, locks at starting balance)',
  '(trailing)': '(trailing)',
  '(estático)': '(static)',
  'Pico: {v}': 'Peak: {v}',
  'Piso: {v}': 'Floor: {v}',
  'Acumulado: {v}': 'Total: {v}',
  'Objetivo alcanzado': 'Target reached',
  'Te falta {v}': '{v} to go',
  'Días operados': 'Trading days',
  'Mínimo cumplido': 'Minimum met',
  'Te falta 1 día con trades': '1 more trading day needed',
  'Te faltan {n} días con trades': '{n} more trading days needed',
  'máx.': 'max',
  'Se mide cuando tengas ganancia acumulada.': 'Measured once you have cumulative profit.',
  'Tu mejor día ({best}) es el {pct}% de la ganancia total.': 'Your best day ({best}) is {pct}% of total profit.',
  'Dentro de la regla.': 'Within the rule.',
  'Supera el máximo: necesitás más días en verde.': 'Above the max: you need more green days.',
  'Marcar como {status}': 'Mark as {status}',
  'Cargá las reglas de esta cuenta en Ajustes → Cuentas.': 'Add this account\'s rules in Settings → Accounts.',

  // ---- Onboarding ----
  'Paso 1 de 3': 'Step 1 of 3',
  'Paso 2 de 3': 'Step 2 of 3',
  'Paso 3 de 3': 'Step 3 of 3',
  '¿Cómo operás?': 'How do you trade?',
  'Así adaptamos tu journal a tu tipo de cuenta.': 'So we can tailor your journal to your account type.',
  'Trader retail': 'Retail trader',
  'Opero mi propia cuenta.': 'I trade my own account.',
  'Opero con una prop firm y tengo reglas de drawdown.': 'I trade with a prop firm and have drawdown rules.',
  'Drawdown diario (%)': 'Daily drawdown (%)',
  'Drawdown total (%)': 'Max drawdown (%)',
  'Profit target (%)': 'Profit target (%)',
  'Drawdown total': 'Max drawdown',
  'Ej. 5': 'E.g. 5',
  'Ej. 10': 'E.g. 10',
  'Ej. 8': 'E.g. 8',
  'Escribí las reglas que tiene que cumplir cada trade para ser válido. En cada operación vas a confirmar si las respetaste.': "Write the rules every trade must follow to be valid. On each trade you'll confirm whether you followed them.",
  'Mínimo 2 reglas': 'At least 2 rules',
  'Nueva regla': 'New rule',
  'Ej. Entré solo dentro de mi horario operativo': 'E.g. I only entered within my trading hours',
  'Ej. De 9:30 a 11:00 hora de Nueva York': 'E.g. From 9:30 to 11:00 New York time',
  '+ Agregar regla': '+ Add rule',
  'Todavía no agregaste reglas. Empezá por la más importante de tu estrategia.': "You haven't added any rules yet. Start with the most important one in your strategy.",
  '{n} reglas cargadas': '{n} rules added',
  '{n} de {min} reglas mínimas': '{n} of {min} minimum rules',
  'Agregá al menos {n} reglas a tu Trading Plan para seguir.': 'Add at least {n} rules to your Trading Plan to continue.',
  'Tu riesgo máximo por día': 'Your max risk per day',
  'Cuánto estás dispuesto a arriesgar como máximo en un día. Te avisamos cuando te acerques y marcamos los días en que te pasaste.': "The most you're willing to risk in a day. We'll warn you when you get close and flag the days you went over.",
  'Riesgo máximo diario (%)': 'Max daily risk (%)',
  'Ingresá un número mayor a 0 y hasta 100 (ej. 1).': 'Enter a number greater than 0 and up to 100 (e.g. 1).',
  'Revisá las reglas de tu prop firm (paso 1): tienen que ser números entre 0 y 100 (ej. 5).': 'Check your prop firm rules (step 1): they must be numbers between 0 and 100 (e.g. 5).',
  'Atrás': 'Back',
  'Siguiente': 'Next',
  'Empezar a operar': 'Start trading',

  // ---- Importador (texto fijo) ----
  'Importar trades': 'Import trades',
  'Exportá el historial de operaciones de tu plataforma como CSV y subilo acá. Todo se procesa en tu navegador.': 'Export your trade history from your platform as a CSV and upload it here. Everything is processed in your browser.',
  'Elegir archivo': 'Choose file',
  'CSV separado por comas, punto y coma o tabulaciones.': 'CSV separated by commas, semicolons or tabs.',
  'La primera fila tiene los nombres de las columnas': 'The first row has the column names',
  '¿Qué es cada columna?': 'What is each column?',
  'Elegí la columna de cada dato. Solo la fecha y el resultado son obligatorios.': 'Pick the column for each field. Only the date and the result are required.',
  'Cómo leer los datos': 'How to read the data',
  'El resultado está en': 'The result is in',
  'Dinero (USD)': 'Money (USD)',
  '% de la cuenta': '% of the account',
  'Tamaño de la cuenta (USD)': 'Account size (USD)',
  'Queda guardado en la cuenta.': 'It is saved to the account.',
  'Ej. 50000': 'E.g. 50000',
  'Formato de fecha': 'Date format',
  'Detectar solo': 'Detect automatically',
  'Día/mes/año': 'Day/month/year',
  'Mes/día/año': 'Month/day/year',
  'Año-mes-día': 'Year-month-day',
  'Las horas del archivo están en': 'Times in the file are in',
  'Hora NY': 'NY time',
  'Mi hora': 'My time',
  'UTC': 'UTC',
  'Revisá antes de importar': 'Review before importing',
  '¿Estos trades respetaron tu Trading Plan?': 'Did these trades follow your Trading Plan?',
  'Sí, todos': 'Yes, all of them',
  'Cuentan como plan seguido.': 'They count as plan followed.',
  'No, o no sé': "No, or I don't know",
  'Cuentan como plan roto hasta que los revises.': 'They count as plan broken until you review them.',
  'Quedan marcados <b>por completar</b>: editalos para sumar las reglas, la emoción, los errores y notas.': 'They are marked <b>to complete</b>: edit them to add the rules, emotion, mistakes and notes.',
};
