// Traducción al inglés. Clave: el texto original en español, tal cual aparece
// en el código o en el HTML. Ver js/i18n.js.
const I18N_EN = {
  // ---- Marco de la app y navegación ----
  'Mi journal · Journal Trading': 'My journal · Journal Trading',
  'Journal Trading': 'Journal Trading',
  'Inicio': 'Home',
  'curva|Inicio': 'Start',
  'Trade': 'Trade',
  'Stats': 'Stats',
  'Estadísticas': 'Statistics',
  'Calendario': 'Calendar',
  'Historial': 'History',
  'Revisión': 'Review',
  'Revisión semanal': 'Weekly review',
  'Ajustes': 'Settings',
  'Cerrar sesión': 'Log out',
  'Salir': 'Log out',
  'No soy yo · Cerrar sesión': 'Not me · Log out',
  'Cerrar': 'Close',
  'Cuenta que estás viendo': 'Account you are viewing',
  'Cambiar a modo claro': 'Switch to light mode',
  'Cambiar a modo oscuro': 'Switch to dark mode',
  'Guardado': 'Saved',

  // ---- Plan y prueba ----
  'Pro · anual': 'Pro · yearly',
  'Pro · mensual': 'Pro · monthly',
  'Prueba gratis': 'Free trial',
  'Prueba terminada': 'Trial ended',
  'queda 1 día': '1 day left',
  'quedan {n} días': '{n} days left',
  'por año · {price}/mes': 'per year · {price}/month',
  'Tu prueba gratis terminó': 'Your free trial has ended',
  'Pasate a Pro': 'Upgrade to Pro',
  'Pasar a Pro': 'Upgrade to Pro',
  'Pasate a Pro para seguir registrando trades. Tus datos siguen guardados.': 'Upgrade to Pro to keep logging trades. Your data is still saved.',
  'Seguí entrenando tu disciplina sin límite de tiempo.': 'Keep training your discipline with no time limit.',
  '¡Listo, ya sos Pro!': "Done, you're Pro now!",
  'Seguí registrando tus trades sin límite.': 'Keep logging your trades with no limits.',
  'Mensual': 'Monthly',
  'por mes': 'per month',
  'Anual': 'Yearly',
  '20% de descuento pagando anual.': '20% off when you pay yearly.',
  'Ahora no': 'Not now',
  'Descargar mis datos': 'Download my data',
  'Tu plan': 'Your plan',
  'anual': 'yearly',
  'mensual': 'monthly',
  '/año': '/year',
  '/mes': '/month',
  'Miembro desde {since}.': 'Member since {since}.',
  'Te queda 1 día de prueba.': 'You have 1 trial day left.',
  'Te quedan {n} días de prueba.': 'You have {n} trial days left.',
  'Tu prueba terminó.': 'Your trial has ended.',

  // ---- Inicio (texto fijo) ----
  'Revisar semana': 'Review week',
  'Ver stats': 'See stats',
  'Tu día de hoy': 'Your day today',
  'Meta del mes': 'Monthly goal',
  'Cambiar meta →': 'Change goal →',
  'Cuánto margen te queda según las reglas de tu prop firm.': 'How much room you have left under your prop firm rules.',
  'Tu semana': 'Your week',
  'Calendario →': 'Calendar →',
  'Últimos trades': 'Latest trades',
  'Historial →': 'History →',
  'Lo que dicen tus datos': 'What your data says',
  'Ver todos →': 'See all →',
  'Logros': 'Achievements',

  // ---- Registrar trade ----
  'Registrar trade': 'Log trade',
  'Editar trade': 'Edit trade',
  'Agregar trade': 'Add trade',
  'Guardar cambios': 'Save changes',
  'Cancelar edición': 'Cancel editing',
  'Paso 1 de 4': 'Step 1 of 4',
  'Paso 2 de 4': 'Step 2 of 4',
  'Paso 3 de 4': 'Step 3 of 4',
  'Paso 4 de 4': 'Step 4 of 4',
  '{n} de 4 secciones completas': '{n} of 4 sections complete',
  'Tu Trading Plan': 'Your Trading Plan',
  'Tocá cada regla que cumpliste': 'Tap each rule you followed',
  'Todavía no armaste tu Trading Plan. Cargá las reglas que tiene que cumplir cada trade y acá vas a poder tildarlas.': "You haven't built your Trading Plan yet. Add the rules every trade must follow and you'll be able to check them off here.",
  'Armar mi Trading Plan': 'Build my Trading Plan',
  'Cumpliste <b>{done}/{total}</b> reglas': 'You followed <b>{done}/{total}</b> rules',
  'Dentro del plan': 'Within plan',
  'Fuera del plan': 'Off plan',
  'Sin marcar': 'Not checked',
  'El trade': 'The trade',
  'Qué operaste y cómo salió': 'What you traded and how it went',
  'Cuenta': 'Account',
  'Resultado': 'Result',
  'Ganador': 'Winner',
  'Perdedor': 'Loser',
  'Break even': 'Break even',
  'TP': 'TP',
  'SL': 'SL',
  'BE': 'BE',
  'Dirección': 'Direction',
  'Long': 'Long',
  'Short': 'Short',
  'Activo': 'Asset',
  'Ej. NQ, EURUSD': 'E.g. NQ, EURUSD',
  'Fecha y hora de entrada': 'Entry date and time',
  'hora de Nueva York': 'New York time',
  'tu hora local': 'your local time',
  'Sesión: {s}': 'Session: {s}',
  'Cuenta para el día {d}': 'Counts for {d}',
  '{time} tu hora': '{time} your time',
  'Setup': 'Setup',
  'Ej. Sweep + IFVG': 'E.g. Sweep + IFVG',
  'Riesgo (%)': 'Risk (%)',
  'Ej. 0.5': 'E.g. 0.5',
  'R:R planeado': 'Planned R:R',
  'Ej. 2 (para 1:2)': 'E.g. 2 (for 1:2)',
  'Resultado real (%)': 'Actual result (%)',
  'Ej. 1.2 o -0.5': 'E.g. 1.2 or -0.5',
  'R real': 'Actual R',
  'R real: {r}': 'Actual R: {r}',
  'Duración (minutos)': 'Duration (minutes)',
  'Ej. 12': 'E.g. 12',
  'Tu cabeza': 'Your mindset',
  'Cómo estabas cuando entraste': 'How you felt when you entered',
  '¿Cómo te sentías al entrar?': 'How did you feel when you entered?',
  'Estados que ayudan': 'Helpful states',
  'Estados de riesgo': 'Risky states',
  'Tranquilo': 'Calm',
  'Confiado': 'Confident',
  'Ansioso': 'Anxious',
  'Revancha': 'Revenge',
  'Aburrido': 'Bored',
  'Nivel de confianza en el trade': 'Confidence in the trade',
  'Confianza 1': 'Confidence 1',
  'Confianza 2': 'Confidence 2',
  'Confianza 3': 'Confidence 3',
  'Confianza 4': 'Confidence 4',
  'Confianza 5': 'Confidence 5',
  'Nada seguro': 'Not sure at all',
  'Poco seguro': 'Slightly sure',
  'Neutral': 'Neutral',
  'Bastante seguro': 'Fairly sure',
  'Totalmente seguro': 'Completely sure',
  '¿Cometiste algún error?': 'Did you make any mistakes?',
  '(podés marcar varios)': '(you can pick several)',
  'Moví el stop': 'Moved my stop',
  'Cerré antes de tiempo': 'Closed too early',
  'Entré tarde': 'Entered late',
  'Entré sin confirmación': 'Entered without confirmation',
  'Sobreoperé': 'Overtraded',
  'Aumenté el tamaño': 'Sized up',
  'No respeté el TP': "Didn't respect my TP",
  'Notas': 'Notes',
  'Lo que querés recordar de este trade': 'What you want to remember about this trade',
  '¿Qué pasó en el desarrollo del trade?': 'What happened during the trade?',
  '(opcional)': '(optional)',
  'Ej. Esperé la confirmación, pero cerré antes por miedo a que volviera.': 'E.g. I waited for confirmation, but closed early out of fear it would reverse.',
  'Arrastrá la imagen acá o': 'Drag the image here or',
  'elegí un archivo': 'choose a file',
  'PNG o JPG · también podés pegarla con Ctrl+V': 'PNG or JPG · you can also paste it with Ctrl+V',
  'Captura del trade': 'Trade screenshot',
  'Cambiar': 'Change',
  'Quitar': 'Remove',
  'Vista previa': 'Preview',
  'Completá el formulario y el trade se arma acá.': 'Fill in the form and your trade takes shape here.',
  'Plan respetado': 'Plan followed',
  'Sí': 'Yes',
  'No': 'No',
  'Emoción': 'Emotion',
  'Errores': 'Mistakes',
  'Puntaje de disciplina': 'Discipline score',
  'Completá el formulario para ver tu puntaje.': 'Fill in the form to see your score.',
  'Trade ejecutado con disciplina.': 'Trade executed with discipline.',
  'Hay cosas para ajustar.': 'Some things to adjust.',
  'Este trade se alejó de tu plan.': 'This trade drifted from your plan.',
  'El riesgo tiene que ser un número (ej. 0.5).': 'Risk must be a number (e.g. 0.5).',
  'El riesgo tiene que ser mayor a 0 y como máximo 100%.': 'Risk must be greater than 0 and at most 100%.',
  'El R:R planeado tiene que ser un número (ej. 2).': 'Planned R:R must be a number (e.g. 2).',
  'El R:R planeado tiene que ser mayor a 0 (ej. 2 para 1:2).': 'Planned R:R must be greater than 0 (e.g. 2 for 1:2).',
  'La duración tiene que ser un número de minutos (ej. 12).': 'Duration must be a number of minutes (e.g. 12).',
  'La duración no puede ser negativa.': "Duration can't be negative.",
  'Elegí un resultado (Ganador, Perdedor o Break even) antes de registrar.': 'Pick a result (Winner, Loser or Break even) before logging.',
  'El resultado tiene que ser un número (ej. 1.2 o -0.5).': 'Result must be a number (e.g. 1.2 or -0.5).',
  'Revisá el resultado: no puede ser mayor a 100% ni menor a -100%.': "Check the result: it can't be above 100% or below -100%.",
  'Marcaste Ganador pero el resultado es negativo. Revisá el resultado o elegí Perdedor.': 'You picked Winner but the result is negative. Check the result or pick Loser.',
  'Marcaste Perdedor pero el resultado es positivo. Revisá el resultado o elegí Ganador.': 'You picked Loser but the result is positive. Check the result or pick Winner.',
  'Revisá la fecha y hora de entrada.': 'Check the entry date and time.',
  'La fecha de entrada no puede ser futura.': "The entry date can't be in the future.",
  'Ese trade ya no existe (se eliminó). No se guardaron los cambios.': 'That trade no longer exists (it was deleted). Your changes were not saved.',
  'No marcaste ninguna regla de tu Trading Plan. Si guardás así, el trade queda como "Plan roto". ¿Guardar igual?': 'You didn\'t check any rule from your Trading Plan. If you save like this, the trade is marked "Plan broken". Save anyway?',
  'No se pudo guardar el trade porque el almacenamiento del navegador está lleno. Exportá un backup y liberá espacio.': "The trade couldn't be saved because browser storage is full. Export a backup and free up space.",

  // ---- Estadísticas, historial y revisión (texto fijo) ----
  'Período': 'Period',
  'Esta semana': 'This week',
  'Este mes': 'This month',
  '3 meses': '3 months',
  'Todo': 'All',
  'Disciplina': 'Discipline',
  'Trades con tu plan respetado contra tu meta.': 'Trades that followed your plan vs. your goal.',
  'Curva de resultados': 'Equity curve',
  'Resultado real': 'Actual result',
  'Si hubieras seguido tu plan': 'If you had followed your plan',
  'Lo que te costó romperlo': 'What breaking it cost you',
  'Plan roto': 'Plan broken',
  'Plan seguido': 'Plan followed',
  'Patrones que aparecen en tus trades del período.': 'Patterns showing up in your trades for this period.',
  'Mapa de calor: cuándo rompés el plan': 'Heatmap: when you break your plan',
  'Cada celda es un día y una hora de entrada, en hora de Nueva York. Pasá el mouse para ver el detalle.': 'Each cell is an entry day and hour, in New York time. Hover to see the details.',
  'El número es la cantidad de trades': 'The number is the trade count',
  'Desglose': 'Breakdown',
  'Sesión': 'Session',
  'Plan seguido vs. plan roto': 'Plan followed vs. plan broken',
  'Lo mismo medido de los dos lados.': 'The same metrics on both sides.',
  'Qué regla cumplís más': 'Which rules you follow most',
  'Porcentaje de trades en los que tildaste cada regla.': 'Share of trades where you checked each rule.',
  'Cierre mensual': 'Monthly close',
  'Cada mes se cierra solo al terminar. Siempre muestra todo tu historial.': 'Each month closes automatically when it ends. It always shows your full history.',
  'Hoy': 'Today',
  'Mes': 'Month',
  'Año': 'Year',
  'Anterior': 'Previous',
  'Buscar por activo, setup o nota': 'Search by asset, setup or note',
  'Buscar trades': 'Search trades',
  'Ordenar': 'Sort',
  'Más recientes': 'Newest',
  'Más antiguos': 'Oldest',
  'Mejor resultado': 'Best result',
  'Peor resultado': 'Worst result',
  'Mayor riesgo': 'Highest risk',
  'Ganadores': 'Winners',
  'Perdedores': 'Losers',
  'Con errores': 'With mistakes',
  'Con captura': 'With screenshot',
  'Por completar': 'To complete',
  'Semana anterior': 'Previous week',
  'Semana siguiente': 'Next week',
  'Resultado por día': 'Result by day',
  'Trades de la semana': "This week's trades",
  'Revisión guiada': 'Guided review',
  'Cinco minutos al final de la semana para mirar cómo operaste, no solo cuánto ganaste.': 'Five minutes at the end of the week to look at how you traded, not just how much you made.',
  'Lo que hiciste bien': 'What you did well',
  '¿Qué hiciste bien esta semana?': 'What did you do well this week?',
  'Ej. Esperé la confirmación en todos los trades y respeté el horario.': 'E.g. I waited for confirmation on every trade and stuck to my hours.',
  'El error que se repitió': 'The mistake that repeated',
  '¿Qué error se repitió y por qué creés que pasó?': 'Which mistake repeated and why do you think it happened?',
  'Ej. Cerré antes de tiempo dos veces por miedo a devolver la ganancia.': 'E.g. I closed early twice out of fear of giving back profit.',
  'Qué vas a cambiar': "What you'll change",
  '¿Qué vas a hacer distinto la semana que viene?': 'What will you do differently next week?',
  '(va a ser tu compromiso)': "(it'll be your commitment)",
  'Ej. Dejar correr el trade hasta el TP salvo que se invalide el setup.': 'E.g. Let the trade run to TP unless the setup is invalidated.',
  'Del 1 al 10, ¿cómo calificás tu disciplina esta semana?': 'From 1 to 10, how would you rate your discipline this week?',
  'Guardar revisión': 'Save review',
  'Revisiones anteriores': 'Past reviews',
  'Cómo evoluciona tu nota de disciplina semana a semana.': 'How your discipline score evolves week by week.',
  '+ Registrar trade en este día': '+ Log a trade on this day',

  // ---- Ajustes ----
  'Perfil': 'Profile',
  'Cómo te ves en la app y en qué plan estás.': 'How you appear in the app and which plan you are on.',
  'Nombre': 'Name',
  'Email': 'Email',
  'Color del avatar': 'Avatar color',
  'Color por defecto': 'Default color',
  'Color {c}': 'Color {c}',
  'Idioma · Language': 'Language · Idioma',
  'Metas y riesgo': 'Goals and risk',
  'Los límites que te ponés para operar con disciplina.': 'The limits you set to trade with discipline.',
  'Meta del mes: trades con el plan respetado': 'Monthly goal: trades that followed the plan',
  'Ej. 80': 'E.g. 80',
  'Meta personalizada': 'Custom goal',
  'Todavía no registraste trades este mes. La meta es que el <b>{goal}%</b> respete tu plan.': "You haven't logged trades this month yet. The goal is for <b>{goal}%</b> to follow your plan.",
  'Este mes vas <b>{pct}%</b> ({done}/{n})': 'This month you are at <b>{pct}%</b> ({done}/{n})',
  'Vas cumpliendo la meta. Mantenela hasta fin de mes.': "You're on track. Keep it up until the end of the month.",
  'Este mes ya no se puede llegar al 100%.': "100% is no longer reachable this month.",
  'Te falta <b>1</b> trade seguido respetando el plan para llegar.': 'You need <b>1</b> more trade in a row following the plan to get there.',
  'Te faltan <b>{n}</b> trades seguidos respetando el plan para llegar.': 'You need <b>{n}</b> trades in a row following the plan to get there.',
  'Riesgo máximo por día según tu Trading Plan': 'Max risk per day according to your Trading Plan',
  'Ej. 1': 'E.g. 1',
  'Riesgo personalizado': 'Custom risk',
  'Elegí tu riesgo máximo diario para ver cuánto te queda cada día.': 'Set your max daily risk to see how much you have left each day.',
  'Riesgo tomado hoy': 'Risk taken today',
  'Límite superado': 'Limit exceeded',
  'Límite alcanzado': 'Limit reached',
  'Cerca del límite': 'Close to the limit',
  'Dentro del límite': 'Within the limit',
  'Arriesgaste {used}% y tu máximo es {max}%. Hoy rompiste tu risk management.': 'You risked {used}% and your max is {max}%. You broke your risk management today.',
  'Ya usaste todo tu riesgo de hoy. Lo que sigue es fuera de plan.': "You've used all your risk for today. Anything else is off plan.",
  'Te quedan {n}% de riesgo para hoy.': 'You have {n}% risk left for today.',
  'Horarios': 'Time',
  'Las estadísticas, el calendario y las sesiones se calculan siempre en hora de Nueva York, la referencia del trading.': 'Statistics, the calendar and sessions are always calculated in New York time, the trading standard.',
  'Mostrar y cargar las horas en': 'Show and enter times in',
  'Hora de Nueva York': 'New York time',
  'Mi hora local': 'My local time',
  'Tu hora local coincide con la de Nueva York.': 'Your local time matches New York time.',
  'Ahora son las {ny} en Nueva York y las {local} en tu zona ({zone}).': "It's {ny} in New York and {local} in your time zone ({zone}).",
  'El día de trading termina a las': 'The trading day ends at',
  'Medianoche NY': 'NY midnight',
  '17:00 NY (forex y futuros)': '5:00 PM NY (forex and futures)',
  'Lo que operes desde las 17:00 de NY cuenta para el día siguiente, como el cierre de forex y futuros.': 'Anything you trade from 5:00 PM NY counts for the next day, like the forex and futures close.',
  'Cada día va de 00:00 a 23:59 en hora de Nueva York.': 'Each day runs from 00:00 to 23:59 New York time.',
  'Sesiones y killzones': 'Sessions and killzones',
  '(hora de Nueva York)': '(New York time)',
  'Nombre de la sesión': 'Session name',
  'Empieza (hora NY)': 'Starts (NY time)',
  'Termina (hora NY)': 'Ends (NY time)',
  'a': 'to',
  '{from} a {to} en tu hora': '{from} to {to} your time',
  'Eliminar sesión': 'Delete session',
  'Sin sesiones: todos los trades quedan "Fuera de sesión".': 'No sessions: every trade is "Outside session".',
  'Poné un nombre a la sesión.': 'Give the session a name.',
  'Completá la hora de inicio y de fin.': 'Fill in the start and end time.',
  'La sesión tiene que empezar y terminar a horas distintas.': 'The session must start and end at different times.',
  'Podés tener hasta 12 sesiones.': 'You can have up to 12 sessions.',
  'Nueva sesión': 'New session',
  '+ Agregar sesión': '+ Add session',
  '+ Killzones ICT': '+ ICT killzones',
  'Volver a las de siempre': 'Reset to defaults',
  '¿Volver a las sesiones de siempre (Asia, Londres y Nueva York)? Se borran las que agregaste.': 'Reset to the default sessions (Asia, London and New York)? The ones you added will be deleted.',
  'Cada trade toma la sesión de su hora de entrada. Si dos se superponen, cuenta la más corta (la killzone gana sobre la sesión entera). Los cambios se aplican también a los trades que ya cargaste.': 'Each trade takes the session of its entry time. If two overlap, the shorter one wins (a killzone wins over the full session). Changes also apply to trades you already logged.',
  'Asia': 'Asia',
  'Londres': 'London',
  'Nueva York': 'New York',
  'Fuera de sesión': 'Outside session',
  'Datos y backup': 'Data and backup',
  'Por ahora tus datos se guardan solo en este navegador. Exportá un backup para no perderlos o pasarlos a otro dispositivo.': 'For now your data is stored only in this browser. Export a backup so you don\'t lose it or to move it to another device.',
  'Exportar backup': 'Export backup',
  'Descargá un archivo con todos tus datos.': 'Download a file with all your data.',
  'Importar backup': 'Import backup',
  'Reemplazá tus datos por los de un archivo.': 'Replace your data with the data in a file.',
  'Importar trades (CSV)': 'Import trades (CSV)',
  'Traé tu historial desde cualquier broker o plataforma. Se suman a los que ya tenés.': 'Bring in your history from any broker or platform. They are added to the ones you already have.',
  'Esto reemplaza todos los datos actuales por los del backup ({n} trades{extra}). ¿Continuar?': 'This replaces all your current data with the backup ({n} trades{extra}). Continue?',
  '; {n} registros dañados se van a descartar': '; {n} damaged records will be discarded',
  'No se pudo leer el archivo.': "The file couldn't be read.",
  'No se pudieron leer tus datos guardados (el archivo está dañado). Se guardó una copia aparte; si tenés un backup, importalo desde Ajustes.': "Your saved data couldn't be read (the file is damaged). A copy was saved separately; if you have a backup, import it from Settings.",
  'No se pudo guardar: el almacenamiento del navegador está lleno. Exportá un backup y borrá trades viejos o imágenes.': "Couldn't save: browser storage is full. Export a backup and delete old trades or images.",
  'No se pudo guardar en el navegador. Exportá un backup desde Ajustes para no perder datos.': "Couldn't save in the browser. Export a backup from Settings so you don't lose data.",
  'Zona peligrosa': 'Danger zone',
  'Borra todos tus trades, rachas y meses cerrados. Tu Trading Plan y tus ajustes se mantienen.': 'Deletes all your trades, streaks and closed months. Your Trading Plan and settings are kept.',
  'Borrar todo el historial': 'Delete all history',
  '¿Seguro? Se borran todos tus trades y no se puede deshacer.': 'Are you sure? All your trades will be deleted and this cannot be undone.',
  'Sí, borrar todo': 'Yes, delete everything',
  'Las reglas que tiene que cumplir cada trade, en el orden en que las revisás.': 'The rules every trade must follow, in the order you check them.',
  'Escribí una nueva regla': 'Write a new rule',
  'Aclaración opcional (ej. 9:30 a 11:00 NY)': 'Optional note (e.g. 9:30 to 11:00 NY)',
  'Agregar': 'Add',
  '+ Agregar aclaración': '+ Add note',
  'Regla': 'Rule',
  'Aclaración (opcional)': 'Note (optional)',
  'Aclaración': 'Note',
  'Subir': 'Move up',
  'Bajar': 'Move down',
  'Editar': 'Edit',
  'Editar regla': 'Edit rule',
  'Eliminar regla': 'Delete rule',
  'Tu Trading Plan está vacío. Agregá la primera regla abajo.': 'Your Trading Plan is empty. Add your first rule below.',
  '¿Eliminar la regla "{rule}" de tu Trading Plan? Los trades que ya cargaste la siguen mostrando como estaba.': 'Delete the rule "{rule}" from your Trading Plan? Trades you already logged keep showing it as it was.',
  '{n} regla': '{n} rule',
  '{n} reglas': '{n} rules',
  'Guardar': 'Save',
  'Cancelar': 'Cancel',
  'Eliminar': 'Delete',
  'Eliminar…': 'Delete…',

  // ---- Cuentas ----
  'Cuentas': 'Accounts',
  'Tu cuenta personal, challenges y cuentas fondeadas, cada una con sus reglas.': 'Your personal account, challenges and funded accounts, each with its own rules.',
  '+ Agregar cuenta': '+ Add account',
  'Mi cuenta': 'My account',
  'Todas las cuentas': 'All accounts',
  '{n} cuenta': '{n} account',
  '{n} cuentas': '{n} accounts',
  '{n} trade': '{n} trade',
  '{n} trades': '{n} trades',
  'Personal': 'Personal',
  'Challenge': 'Challenge',
  'Fondeada': 'Funded',
  'Activa': 'Active',
  'Aprobada': 'Passed',
  'Quemada': 'Failed',
  'Archivada': 'Archived',
  'Cuenta de fondeo': 'Funded account',
  'Cuentas de fondeo': 'Funded accounts',
  'Crear fondeada': 'Create funded',
  '{name} fondeada': '{name} funded',
  'Editar cuenta': 'Edit account',
  'Nueva cuenta': 'New account',
  'Tipo': 'Type',
  'Tu propia cuenta, sin reglas de una prop firm.': 'Your own account, without prop firm rules.',
  'La evaluación de una prop firm: tenés que llegar al objetivo sin romper las reglas.': "A prop firm evaluation: you have to hit the target without breaking the rules.",
  'Cuenta ya fondeada: se cuidan los drawdowns, sin objetivo.': 'Already funded: protect the drawdowns, no target.',
  'Ej. Challenge 50K fase 1': 'E.g. 50K Challenge phase 1',
  'Ej. Mi cuenta': 'E.g. My account',
  'Prop firm': 'Prop firm',
  'Ej. tu prop firm': 'E.g. your prop firm',
  'Tamaño en USD (opcional)': 'Size in USD (optional)',
  'Ej. {v}': 'E.g. {v}',
  'Reglas': 'Rules',
  'Drawdown diario': 'Daily drawdown',
  'Drawdown máximo': 'Max drawdown',
  'Tipo de drawdown máximo': 'Max drawdown type',
  'Estático': 'Static',
  'Trailing': 'Trailing',
  'Profit target': 'Profit target',
  'Días mínimos (opcional)': 'Minimum days (optional)',
  'Consistencia': 'Consistency',
  'Consistencia (opcional)': 'Consistency (optional)',
  'El piso deja de subir cuando llega al balance inicial (mi firma congela el trailing)': 'The floor stops rising once it reaches the starting balance (my firm locks the trailing)',
  'La consistencia limita cuánto puede pesar tu mejor día sobre la ganancia total (ej. 30%: ningún día puede ser más del 30% del total).': 'Consistency limits how much your best day can weigh on total profit (e.g. 30%: no day can be more than 30% of the total).',
  'Estado': 'Status',
  'Poné un nombre para reconocer la cuenta.': 'Give the account a name you will recognize.',
  'El tamaño tiene que ser un número (ej. 50000).': 'Size must be a number (e.g. 50000).',
  'drawdown diario': 'daily drawdown',
  'drawdown máximo': 'max drawdown',
  'el drawdown diario': 'the daily drawdown',
  'el drawdown máximo': 'the max drawdown',
  'profit target': 'profit target',
  'consistencia': 'consistency',
  'Revisá el {rule}: tiene que ser un número entre 0 y 100.': 'Check the {rule}: it must be a number between 0 and 100.',
  'Los días mínimos tienen que ser un número entero (ej. 4).': 'Minimum days must be a whole number (e.g. 4).',
  'No se pudo guardar.': "Couldn't save.",
  '"{acc}" tiene 1 trade. Si la eliminás, pasa a "{other}". Si querés conservarlo aparte, mejor archivala (Estado → Archivada). ¿Eliminar igual?': '"{acc}" has 1 trade. If you delete it, it moves to "{other}". To keep it separate, archive the account instead (Status → Archived). Delete anyway?',
  '"{acc}" tiene {n} trades. Si la eliminás, pasan a "{other}". Si querés conservarlos aparte, mejor archivala (Estado → Archivada). ¿Eliminar igual?': '"{acc}" has {n} trades. If you delete it, they move to "{other}". To keep them separate, archive the account instead (Status → Archived). Delete anyway?',
  '{acc}: ya no te queda margen hasta {which}. Hoy no operes esta cuenta.': "{acc}: you have no room left before {which}. Don't trade this account today.",
  'Cuidado: arriesgás {risk}% y en {acc} te quedan {left}% hasta {which}.': 'Careful: you are risking {risk}% and {acc} only has {left}% left before {which}.',
  '{acc}: te quedan {left} hasta {which}.': '{acc}: {left} left before {which}.',
  'Regla rota': 'Rule broken',
  'Rompiste el {rule} el {date}. Si tu prop firm la dio por perdida, marcala como quemada.': 'You broke the {rule} on {date}. If your prop firm failed the account, mark it as failed.',
  'Objetivo cumplido': 'Target reached',
  'Cumpliste todas las reglas del challenge. Cuando tu firma lo confirme, marcala como aprobada.': 'You met every challenge rule. Once your firm confirms it, mark it as passed.',
  'Falta una regla': 'One rule missing',
  'Llegaste al objetivo pero te faltan días operados.': 'You hit the target but still need more trading days.',
  'Llegaste al objetivo pero tu mejor día pesa demasiado (regla de consistencia).': 'You hit the target but your best day weighs too much (consistency rule).',
  'En curso': 'In progress',
  'te quedan {left}': '{left} left',
  'límite alcanzado': 'limit reached',
  'Hoy: {pnl}': 'Today: {pnl}',
  '(trailing, se congela en el inicial)': '(trailing, locks at starting balance)',
  '(trailing)': '(trailing)',
  '(estático)': '(static)',
  'Pico: {v}': 'Peak: {v}',
  'Piso: {v}': 'Floor: {v}',
  'Acumulado: {v}': 'Total: {v}',
  'Objetivo alcanzado': 'Target reached',
  'Te falta {v}': '{v} to go',
  'Días operados': 'Trading days',
  'Mínimo cumplido': 'Minimum met',
  'Te falta 1 día con trades': '1 more trading day needed',
  'Te faltan {n} días con trades': '{n} more trading days needed',
  'máx.': 'max',
  'Se mide cuando tengas ganancia acumulada.': 'Measured once you have cumulative profit.',
  'Tu mejor día ({best}) es el {pct}% de la ganancia total.': 'Your best day ({best}) is {pct}% of total profit.',
  'Dentro de la regla.': 'Within the rule.',
  'Supera el máximo: necesitás más días en verde.': 'Above the max: you need more green days.',
  'Marcar como {status}': 'Mark as {status}',
  'Cargá las reglas de esta cuenta en Ajustes → Cuentas.': 'Add this account\'s rules in Settings → Accounts.',

  // ---- Onboarding ----
  'Paso 1 de 3': 'Step 1 of 3',
  'Paso 2 de 3': 'Step 2 of 3',
  'Paso 3 de 3': 'Step 3 of 3',
  '¿Cómo operás?': 'How do you trade?',
  'Así adaptamos tu journal a tu tipo de cuenta.': 'So we can tailor your journal to your account type.',
  'Trader retail': 'Retail trader',
  'Opero mi propia cuenta.': 'I trade my own account.',
  'Opero con una prop firm y tengo reglas de drawdown.': 'I trade with a prop firm and have drawdown rules.',
  'Drawdown diario (%)': 'Daily drawdown (%)',
  'Drawdown total (%)': 'Max drawdown (%)',
  'Profit target (%)': 'Profit target (%)',
  'Drawdown total': 'Max drawdown',
  'Ej. 5': 'E.g. 5',
  'Ej. 10': 'E.g. 10',
  'Ej. 8': 'E.g. 8',
  'Escribí las reglas que tiene que cumplir cada trade para ser válido. En cada operación vas a confirmar si las respetaste.': "Write the rules every trade must follow to be valid. On each trade you'll confirm whether you followed them.",
  'Mínimo 2 reglas': 'At least 2 rules',
  'Nueva regla': 'New rule',
  'Ej. Entré solo dentro de mi horario operativo': 'E.g. I only entered within my trading hours',
  'Ej. De 9:30 a 11:00 hora de Nueva York': 'E.g. From 9:30 to 11:00 New York time',
  '+ Agregar regla': '+ Add rule',
  'Todavía no agregaste reglas. Empezá por la más importante de tu estrategia.': "You haven't added any rules yet. Start with the most important one in your strategy.",
  '{n} reglas cargadas': '{n} rules added',
  '{n} de {min} reglas mínimas': '{n} of {min} minimum rules',
  'Agregá al menos {n} reglas a tu Trading Plan para seguir.': 'Add at least {n} rules to your Trading Plan to continue.',
  'Tu riesgo máximo por día': 'Your max risk per day',
  'Cuánto estás dispuesto a arriesgar como máximo en un día. Te avisamos cuando te acerques y marcamos los días en que te pasaste.': "The most you're willing to risk in a day. We'll warn you when you get close and flag the days you went over.",
  'Riesgo máximo diario (%)': 'Max daily risk (%)',
  'Ingresá un número mayor a 0 y hasta 100 (ej. 1).': 'Enter a number greater than 0 and up to 100 (e.g. 1).',
  'Revisá las reglas de tu prop firm (paso 1): tienen que ser números entre 0 y 100 (ej. 5).': 'Check your prop firm rules (step 1): they must be numbers between 0 and 100 (e.g. 5).',
  'Atrás': 'Back',
  'Siguiente': 'Next',
  'Empezar a operar': 'Start trading',

  // ---- Importador (texto fijo) ----
  'Importar trades': 'Import trades',
  'Exportá el historial de operaciones de tu plataforma como CSV y subilo acá. Todo se procesa en tu navegador.': 'Export your trade history from your platform as a CSV and upload it here. Everything is processed in your browser.',
  'Elegir archivo': 'Choose file',
  'CSV separado por comas, punto y coma o tabulaciones.': 'CSV separated by commas, semicolons or tabs.',
  'La primera fila tiene los nombres de las columnas': 'The first row has the column names',
  '¿Qué es cada columna?': 'What is each column?',
  'Elegí la columna de cada dato. Solo la fecha y el resultado son obligatorios.': 'Pick the column for each field. Only the date and the result are required.',
  'Cómo leer los datos': 'How to read the data',
  'El resultado está en': 'The result is in',
  'Dinero (USD)': 'Money (USD)',
  '% de la cuenta': '% of the account',
  'Tamaño de la cuenta (USD)': 'Account size (USD)',
  'Queda guardado en la cuenta.': 'It is saved to the account.',
  'Ej. 50000': 'E.g. 50000',
  'Formato de fecha': 'Date format',
  'Detectar solo': 'Detect automatically',
  'Día/mes/año': 'Day/month/year',
  'Mes/día/año': 'Month/day/year',
  'Año-mes-día': 'Year-month-day',
  'Las horas del archivo están en': 'Times in the file are in',
  'Hora NY': 'NY time',
  'Mi hora': 'My time',
  'UTC': 'UTC',
  'Revisá antes de importar': 'Review before importing',
  '¿Estos trades respetaron tu Trading Plan?': 'Did these trades follow your Trading Plan?',
  'Sí, todos': 'Yes, all of them',
  'Cuentan como plan seguido.': 'They count as plan followed.',
  'No, o no sé': "No, or I don't know",
  'Cuentan como plan roto hasta que los revises.': 'They count as plan broken until you review them.',
  'Quedan marcados <b>por completar</b>: editalos para sumar las reglas, la emoción, los errores y notas.': 'They are marked <b>to complete</b>: edit them to add the rules, emotion, mistakes and notes.',

  // ---- Logros ----
  'Primer paso': 'First step',
  'Registraste tu primer trade.': 'You logged your first trade.',
  'Constante': 'Consistent',
  'Registraste 10 trades.': 'You logged 10 trades.',
  'Disciplina de journal': 'Journal discipline',
  'Registraste 50 trades.': 'You logged 50 trades.',
  'Centenario': 'Centurion',
  'Registraste 100 trades.': 'You logged 100 trades.',
  'Racha de 5': 'Streak of 5',
  '5 trades seguidos respetando tu plan.': '5 trades in a row following your plan.',
  'Racha de 10': 'Streak of 10',
  '10 trades seguidos respetando tu plan.': '10 trades in a row following your plan.',
  'Racha de 25': 'Streak of 25',
  '25 trades seguidos respetando tu plan.': '25 trades in a row following your plan.',
  'Máquina': 'Machine',
  '50 trades seguidos respetando tu plan.': '50 trades in a row following your plan.',
  'Sin errores': 'Mistake-free',
  '10 trades seguidos sin marcar errores.': '10 trades in a row without logging mistakes.',
  'Semana perfecta': 'Perfect week',
  'Una semana con 3 trades o más y el plan siempre respetado.': 'A week with 3 or more trades and the plan always followed.',
  'Meta cumplida': 'Goal met',
  'Cumpliste tu meta de disciplina en un mes (con 10 trades o más y una meta de 70% o más).': 'You hit your discipline goal in a month (with 10+ trades and a goal of 70% or more).',
  'Autoconocimiento': 'Self-awareness',
  'Completaste tu primera revisión semanal.': 'You completed your first weekly review.',
  'Un mes de revisiones': 'A month of reviews',
  'Completaste 4 revisiones semanales.': 'You completed 4 weekly reviews.',
  '¡Logro desbloqueado!': 'Achievement unlocked!',
  '¡Desbloqueaste {n} logros!': 'You unlocked {n} achievements!',
  'Desbloqueado el {date}': 'Unlocked on {date}',
  'Todavía no desbloqueaste logros. El primero llega con tu primer trade.': "You haven't unlocked any achievements yet. The first one comes with your first trade.",
  'Próximo logro': 'Next achievement',
  'Ocultar': 'Hide',
  'Ver todos los logros': 'See all achievements',
  'Vas {n}/10 trades este mes': "You're at {n}/10 trades this month",
  'Vas {pct}% de {target}% de plan este mes': "You're at {pct}% of a {target}% plan goal this month",
  'Vas {cur}/{max}': "You're at {cur}/{max}",

  // ---- Inicio (contenido) ----
  'Buen día': 'Good morning',
  'Buenas tardes': 'Good afternoon',
  'Buenas noches': 'Good evening',
  'Bienvenido a tu journal. Empezá por los tres pasos de abajo.': 'Welcome to your journal. Start with the three steps below.',
  'Operá con un plan. Ejecutá con disciplina.': 'Trade with a plan. Execute with discipline.',
  'Tu compromiso de esta semana': 'Your commitment this week',
  'Regla del día · leela antes de operar': 'Rule of the day · read it before trading',
  'Armá tu Trading Plan': 'Build your Trading Plan',
  'Las reglas que tiene que cumplir cada trade.': 'The rules every trade must follow.',
  'Ir a Ajustes': 'Go to Settings',
  'Registrá tu primer trade': 'Log your first trade',
  'Resultado, plan, emoción y lo que pasó.': 'Result, plan, emotion and what happened.',
  'Hacé tu primera revisión': 'Do your first review',
  'Cinco minutos al final de la semana.': 'Five minutes at the end of the week.',
  'Ir a Revisión': 'Go to Review',
  'Primeros pasos': 'Getting started',
  '{n} de 3': '{n} of 3',
  'Racha actual': 'Current streak',
  'Mejor racha: {n}': 'Best streak: {n}',
  'Resultado semana': 'Week result',
  'Plan semana': 'Week plan',
  'Win rate semana': 'Week win rate',
  '{n} trade esta semana': '{n} trade this week',
  '{n} trades esta semana': '{n} trades this week',
  'Meta: {goal}%': 'Goal: {goal}%',
  'Superaste tu riesgo máximo ({used}% de {max}%). Hoy no operes más.': "You exceeded your max risk ({used}% of {max}%). Don't trade any more today.",
  'Llegaste a tu límite de riesgo. Hoy no operes más.': "You reached your risk limit. Don't trade any more today.",
  'Hoy rompiste el plan {n} veces. ¿Te tomás una pausa?': 'You broke your plan {n} times today. Time for a break?',
  'Rompiste el plan una vez hoy. Bajá el ritmo y revisá tus reglas antes del próximo.': 'You broke your plan once today. Slow down and review your rules before the next one.',
  'Todavía no operaste hoy. Leé tu regla del día antes de entrar.': "You haven't traded today. Read your rule of the day before entering.",
  'Vas bien: todo dentro del plan hoy.': 'Going well: everything within plan today.',
  'Trades': 'Trades',
  'En plan': 'On plan',
  'Fuera de plan': 'Off plan',
  'Riesgo usado hoy': 'Risk used today',
  'Definí tu máximo en Ajustes': 'Set your max in Settings',
  'Sin riesgo disponible': 'No risk left',
  'Te quedan <b>{n}%</b> de riesgo': 'You have <b>{n}%</b> risk left',
  'de {goal}%': 'of {goal}%',
  'Sin trades este mes': 'No trades this month',
  'Te falta 1 punto': '1 point to go',
  'Te faltan {n} puntos': '{n} points to go',
  'Trades en plan': 'Trades on plan',
  'Para llegar': 'To get there',
  '{n} seguidos en plan': '{n} in a row on plan',
  'Quedan': 'Left',
  '1 día del mes': '1 day this month',
  '{n} días del mes': '{n} days this month',
  'Rompiste el plan': 'You broke the plan',
  'Todavía no registraste trades.': "You haven't logged any trades yet.",
  'plan roto': 'plan broken',
  'Con 3 trades o más vas a empezar a ver patrones de tu operativa acá.': "With 3 or more trades you'll start seeing patterns in your trading here.",
  'Todavía no hay patrones claros. Seguí registrando emociones y errores en cada trade.': 'No clear patterns yet. Keep logging emotions and mistakes on every trade.',
  'Trade {n}': 'Trade {n}',
  'Con tu plan': 'With your plan',
  'Registrá al menos un trade para ver tu curva.': 'Log at least one trade to see your curve.',

  // ---- Patrones automáticos ----
  'Lun': 'Mon',
  'Mar': 'Tue',
  'Mié': 'Wed',
  'Jue': 'Thu',
  'Vie': 'Fri',
  'Sáb': 'Sat',
  'Dom': 'Sun',
  'lunes': 'Mondays',
  'martes': 'Tuesdays',
  'miércoles': 'Wednesdays',
  'jueves': 'Thursdays',
  'viernes': 'Fridays',
  'sábados': 'Saturdays',
  'domingos': 'Sundays',
  'Después de una pérdida rompés el plan el <b>{a}</b> de las veces (contra {b} el resto). Ojo con la revancha.': 'After a loss you break your plan <b>{a}</b> of the time (vs. {b} otherwise). Watch out for revenge trading.',
  'Después de una pérdida mantenés la cabeza fría: rompés el plan solo el {a} de las veces.': 'After a loss you keep a cool head: you break your plan only {a} of the time.',
  'Cuando seguís tu plan promediás <b>{f}</b> por trade; cuando lo rompés, <b>{b}</b>.': 'When you follow your plan you average <b>{f}</b> per trade; when you break it, <b>{b}</b>.',
  'Romper el plan ya te costó <b>{sum}</b> en total ({n} trades).': 'Breaking your plan has already cost you <b>{sum}</b> in total ({n} trades).',
  'Tus trades con <b>{emo}</b> promedian <b>{avg}</b> ({n} trades).': 'Your trades while <b>{emo}</b> average <b>{avg}</b> ({n} trades).',
  'Operando <b>{emo}</b> promediás <b>{avg}</b> por trade.': 'Trading <b>{emo}</b> you average <b>{avg}</b> per trade.',
  'Tus trades con <b>{emo}</b> promedian <b>{avg}</b>.': 'Your trades while <b>{emo}</b> average <b>{avg}</b>.',
  'Tu error más repetido es <b>"{err}"</b>: {n} veces, con un resultado promedio de <b>{avg}</b>.': 'Your most repeated mistake is <b>"{err}"</b>: {n} times, with an average result of <b>{avg}</b>.',
  'Tu mejor sesión es <b>{s}</b>: promediás {avg} por trade.': 'Your best session is <b>{s}</b>: you average {avg} per trade.',
  'Tu mejor horario es de <b>{from}:00 a {to}:00</b> hora NY ({avg} por trade).': 'Your best hour is <b>{from}:00 to {to}:00</b> NY time ({avg} per trade).',
  'Entre las {from}:00 y las {to}:00 (hora NY) seguís tu plan solo el {pct} de las veces.': 'Between {from}:00 and {to}:00 (NY time) you follow your plan only {pct} of the time.',
  'Los <b>{day}</b> es cuando más rompés el plan (lo seguís el {pct} de las veces).': '<b>{day}</b> are when you break your plan the most (you follow it {pct} of the time).',
  'Tu intuición funciona: con confianza alta promediás {hi}, con confianza baja {lo}.': 'Your intuition works: with high confidence you average {hi}, with low confidence {lo}.',
  'Cuidado con el exceso de confianza: con confianza alta promediás {hi}, menos que con confianza baja ({lo}).': 'Watch out for overconfidence: with high confidence you average {hi}, less than with low confidence ({lo}).',
  'Te va mejor en <b>{a}</b> ({avgA} por trade) que en {b} ({avgB}).': 'You do better on <b>{a}</b> ({avgA} per trade) than on {b} ({avgB}).',
  'En tus ganadores planeás 1:{planned} pero cobrás {real}R en promedio: estás cerrando antes de tiempo.': "On your winners you plan 1:{planned} but take {real}R on average: you're closing too early.",

  // ---- Estadísticas (contenido) ----
  'Últimos 3 meses': 'Last 3 months',
  'Todo tu historial': 'Your full history',
  'semana pasada': 'last week',
  'mes pasado': 'last month',
  '3 meses anteriores': 'previous 3 months',
  'Todo el historial': 'Full history',
  'Sin período anterior': 'No previous period',
  '= que {label}': 'same as {label}',
  'pts': 'pts',
  '{txt} vs {label}': '{txt} vs {label}',
  'período anterior': 'previous period',
  'Resultado acumulado': 'Cumulative result',
  'Siguió el plan': 'Followed the plan',
  'Win rate': 'Win rate',
  'Resultado prom./trade': 'Avg result/trade',
  'Riesgo promedio': 'Avg risk',
  'Duración promedio': 'Avg duration',
  'R real promedio': 'Avg actual R',
  'plan respetado': 'plan followed',
  'Registrá trades para medir tu disciplina.': 'Log trades to measure your discipline.',
  'Estás arriba de tu meta del {goal}%': "You're above your {goal}% goal",
  'Te faltan {n} pts para tu meta del {goal}%': "You're {n} pts away from your {goal}% goal",
  'trades en plan': 'trades on plan',
  'racha actual': 'current streak',
  'mejor racha': 'best streak',
  'Romper el plan te costó {n} puntos': 'Breaking your plan cost you {n} points',
  'Resultado real {real} · con tu plan habrías hecho {plan}.': 'Actual result {real} · with your plan you would have made {plan}.',
  'Respetaste tu plan en todos los trades': 'You followed your plan on every trade',
  'Resultado del período: {real}. Así se construye un sistema medible.': "Period result: {real}. That's how you build a measurable system.",
  'Con 3 trades o más en el período vas a empezar a ver patrones.': "With 3 or more trades in the period you'll start seeing patterns.",
  'Todavía no hay patrones claros. Registrá emoción, errores, activo y horario en cada trade: cuantos más datos, más patrones aparecen.': 'No clear patterns yet. Log emotion, mistakes, asset and time on every trade: the more data, the more patterns show up.',
  'Lo que te funciona': 'What works for you',
  'Todavía no aparece un patrón positivo claro.': 'No clear positive pattern yet.',
  'Lo que te cuesta plata': 'What costs you money',
  'No aparecen patrones que te estén costando.': 'No patterns costing you money.',
  'Para tener en cuenta': 'Worth noting',
  'Registrá trades con su hora de entrada para ver el mapa.': 'Log trades with their entry time to see the map.',
  '{from}:00 a {to}:00 NY': '{from}:00 to {to}:00 NY',
  'Marcá cómo te sentías al entrar en cada trade para ver este desglose.': 'Log how you felt when entering each trade to see this breakdown.',
  'Error': 'Mistake',
  'Todavía no marcaste errores en tus trades.': "You haven't logged mistakes on your trades yet.",
  'Cargá el activo en tus trades para ver este desglose.': 'Add the asset to your trades to see this breakdown.',
  'Cargá el setup en tus trades para ver este desglose.': 'Add the setup to your trades to see this breakdown.',
  'Marcá si fue long o short para ver este desglose.': 'Mark whether it was long or short to see this breakdown.',
  'Prom./trade': 'Avg/trade',
  'Total': 'Total',
  'Todavía no hay datos.': 'No data yet.',
  'Mejor': 'Best',
  'Peor': 'Worst',
  'Todavía no hay trades en el período.': 'No trades in this period yet.',
  'Duración': 'Duration',
  'Acumulado': 'Cumulative',
  'Armá tu Trading Plan en Ajustes para ver qué reglas cumplís más.': 'Build your Trading Plan in Settings to see which rules you follow most.',
  'Tus reglas actuales son más nuevas que los trades del período.': 'Your current rules are newer than the trades in this period.',
  'Meta no cumplida': 'Goal not met',
  '<b>{n}</b> trades': '<b>{n}</b> trades',
  '<b>{n}</b> por día operado': '<b>{n}</b> per trading day',
  '<b>{n}</b> risk mgmt': '<b>{n}</b> risk mgmt',

  // ---- Calendario ----
  'No registraste trades en {period}.': 'You did not log trades in {period}.',
  '{g} verdes · {r} rojos': '{g} green · {r} red',
  'Mejor día': 'Best day',
  'Peor día': 'Worst day',
  'Días en verde': 'Green days',
  'Días seguidos en verde': 'Green days in a row',
  '1 día': '1 day',
  '{n} días': '{n} days',
  'Semana': 'Week',
  '{n}% plan': '{n}% plan',
  'Sin trades': 'No trades',
  'Mejor mes': 'Best month',
  'Peor mes': 'Worst month',
  'Meses en verde': 'Green months',
  '{n} de {total}': '{n} of {total}',
  'Meses con trades': 'Months with trades',
  'Plan siempre seguido': 'Plan always followed',
  'A veces roto': 'Sometimes broken',
  'Siempre roto': 'Always broken',
  'Trade con plan seguido': 'Trade with plan followed',
  'Pérdida': 'Loss',
  'Ganancia': 'Profit',
  'No registraste trades este día.': "You didn't log trades on this day.",
  'R total': 'Total R',
  'Faltó del plan: {rules}': 'Missed from plan: {rules}',
  'Ver detalle': 'See details',

  // ---- Historial ----
  'Trades filtrados': 'Filtered trades',
  'Limpiar filtros': 'Clear filters',
  '{n} por completar': '{n} to complete',
  'Importar CSV': 'Import CSV',
  'Exportar CSV': 'Export CSV',
  'Riesgo {n}%': 'Risk {n}%',
  '{n} fuera de plan': '{n} off plan',
  'Ningún trade coincide con los filtros': 'No trades match the filters',
  'Probá con otra búsqueda o sacá algún filtro.': 'Try another search or remove a filter.',
  'Todavía no registraste ningún trade': "You haven't logged any trades yet",
  'Cada trade que cargues aparece acá con su resultado, tu plan, tu emoción y tus notas.': 'Every trade you log shows up here with its result, your plan, your emotion and your notes.',
  'Mostrando {n} de {total}': 'Showing {n} of {total}',
  'Cargar más': 'Load more',
  'Mostrando los {n} trades': 'Showing all {n} trades',
  '(regla que ya no está en tu plan)': '(rule no longer in your plan)',
  'Riesgo': 'Risk',
  'Importado · por completar': 'Imported · to complete',
  'Disciplina {n}/100': 'Discipline {n}/100',
  'Risk management roto ese día': 'Risk management broken that day',
  'Seguido': 'Followed',
  'Roto': 'Broken',
  'No tenías reglas cargadas.': "You didn't have any rules set.",
  'Confianza': 'Confidence',
  'Sin errores marcados.': 'No mistakes logged.',
  'Qué pasó en el trade': 'What happened in the trade',
  'Sin comentarios.': 'No comments.',
  '¿Eliminar este trade? No se puede deshacer.': 'Delete this trade? This cannot be undone.',
  'Fecha': 'Date',
  'Hora': 'Time',
  'Hora (NY)': 'Time (NY)',
  'Resultado %': 'Result %',
  'Riesgo %': 'Risk %',
  'Duración (min)': 'Duration (min)',
  'Reglas que faltaron': 'Missed rules',
  'Nota': 'Note',

  // ---- Revisión ----
  'Excelente': 'Excellent',
  'Sólida': 'Solid',
  'Regular': 'Fair',
  'Floja': 'Weak',
  'Semana pasada': 'Last week',
  'Revisada': 'Reviewed',
  'Pendiente': 'Pending',
  '1 semana revisada': '1 week reviewed',
  '{n} semanas seguidas revisando': '{n} weeks in a row reviewing',
  'Tu compromiso para esta semana': 'Your commitment for this week',
  'Sin semana previa para comparar': 'No previous week to compare',
  '= que la semana pasada': 'same as last week',
  '{txt} vs semana pasada': '{txt} vs last week',
  '{n} la semana pasada': '{n} last week',
  'Meta {goal}%': 'Goal {goal}%',
  'sin trades': 'no trades',
  'No registraste trades esta semana.': "You didn't log trades this week.",
  'Error más repetido': 'Most repeated mistake',
  '1 vez': 'once',
  '{n} veces': '{n} times',
  '<b>No marcaste errores</b> esta semana': '<b>No mistakes logged</b> this week',
  'Emoción más frecuente': 'Most frequent emotion',
  '{avg} promedio': '{avg} average',
  '<b>1 trade</b> fuera de plan · sumó {sum}': '<b>1 trade</b> off plan · totaling {sum}',
  '<b>{n} trades</b> fuera de plan · sumaron {sum}': '<b>{n} trades</b> off plan · totaling {sum}',
  'Plan': 'Plan',
  '<b>Respetaste tu plan</b> en todos los trades': '<b>You followed your plan</b> on every trade',
  'en {asset}': 'on {asset}',
  'Mejor y peor trade': 'Best and worst trade',
  'Ver el trade de la semana': "See this week's trade",
  'Ver los {n} trades de la semana': "See this week's {n} trades",
  'Actualizar revisión': 'Update review',
  'Tenés cambios sin guardar en esta semana.': 'You have unsaved changes for this week.',
  'Guardada el {date}': 'Saved on {date}',
  '{n} de 10': '{n} of 10',
  'Nota de disciplina': 'Discipline score',
  'Promedio <b>{n}</b>': 'Average <b>{n}</b>',
  'Todavía no hiciste ninguna revisión': "You haven't done any reviews yet",
  'Respondé las tres preguntas y calificá tu semana. Te lleva cinco minutos y es donde más se aprende.': "Answer the three questions and rate your week. It takes five minutes and it's where you learn the most.",
  'Desbloquea el logro "Autoconocimiento"': 'Unlocks the "Self-awareness" achievement',
  'Es momento de revisar tu semana': "It's time to review your week",
  '1 trade sin revisar. Te lleva cinco minutos.': '1 trade to review. It takes five minutes.',
  '{n} trades sin revisar. Te lleva cinco minutos.': '{n} trades to review. It takes five minutes.',
  'Revisar ahora': 'Review now',
  'Respondé al menos una pregunta para guardar la revisión.': 'Answer at least one question to save the review.',
  'Revisión guardada.': 'Review saved.',

  // ---- Importador (contenido) ----
  'Hora de entrada (si viene en otra columna)': 'Entry time (if in a separate column)',
  'Fecha y hora de salida (para la duración)': 'Exit date and time (for duration)',
  'Dirección (compra / venta)': 'Direction (buy / sell)',
  'Comisiones (se restan del resultado)': 'Fees (subtracted from the result)',
  'Columna {n}': 'Column {n}',
  'no se entiende la fecha "{v}"': 'the date "{v}" is not recognized',
  'la fecha es futura': 'the date is in the future',
  'el resultado "{v}" no es un número': 'the result "{v}" is not a number',
  'falta el tamaño de la cuenta': 'the account size is missing',
  'el resultado da {n}%: revisá el tamaño de la cuenta o la columna': 'the result comes out to {n}%: check the account size or the column',
  'Revisar': 'Review',
  'Detectado: {fmt}.': 'Detected: {fmt}.',
  'año-mes-día': 'year-month-day',
  'día/mes/año': 'day/month/year',
  'mes/día/año': 'month/day/year',
  'No se puede saber si es día/mes o mes/día (ningún día pasa de 12). Se usa día/mes/año: elegilo a mano si tu archivo es mes/día.': "Can't tell whether it's day/month or month/day (no day is above 12). Using day/month/year: pick it manually if your file is month/day.",
  'El resultado ya está en % de la cuenta.': 'The result is already in % of the account.',
  'Se pasa a % con el tamaño de "{acc}": {size}.': 'Converted to % using the size of "{acc}": {size}.',
  'Para pasarlo a % hace falta el tamaño de la cuenta.': 'The account size is needed to convert it to %.',
  'trade nuevo': 'new trade',
  'trades nuevos': 'new trades',
  'fila con error': 'row with errors',
  'filas con error': 'rows with errors',
  'Fila {n}: {msg}': 'Row {n}: {msg}',
  '…y {n} más.': '…and {n} more.',
  'y {n} más': 'and {n} more',
  '1 fila': '1 row',
  '{n} filas': '{n} rows',
  'Importar': 'Import',
  'Importar 1 trade': 'Import 1 trade',
  'Importar {n} trades': 'Import {n} trades',
  '1 trade importado': '1 trade imported',
  '{n} trades importados': '{n} trades imported',
  'El archivo es muy grande (máximo 5 MB).': 'The file is too large (max 5 MB).',
  'No se encontraron columnas. Exportá el historial como CSV (separado por comas o punto y coma).': 'No columns found. Export your history as CSV (separated by commas or semicolons).',
  'Elegí la columna de la fecha de entrada.': 'Pick the entry date column.',
  'Elegí la columna del resultado.': 'Pick the result column.',
  'Ingresá el tamaño de la cuenta en USD (ej. 50000) para pasar el resultado a %.': 'Enter the account size in USD (e.g. 50000) to convert the result to %.',
  'Elegí si estos trades respetaron tu Trading Plan.': 'Choose whether these trades followed your Trading Plan.',
  'No se pudo guardar: el almacenamiento del navegador está lleno.': "Couldn't save: browser storage is full.",
  'Quedan "por completar": sumales emoción, errores y notas.': 'They are marked "to complete": add emotion, mistakes and notes.',

  // ---- Backup ----
  'El archivo no es un backup válido (no se pudo leer).': "The file isn't a valid backup (it couldn't be read).",
  'El archivo no parece un backup del journal.': "The file doesn't look like a journal backup.",
  'El backup es de una versión más nueva de la app.': 'The backup is from a newer version of the app.',

  // ---- Landing ----
  'Journal Trading · Primero la mente, después los resultados': 'Journal Trading · Mindset first, results follow',
  'El journal de trading enfocado en la psicología: entrená tu disciplina trade por trade hasta operar como una máquina. Los resultados llegan después.': 'The trading journal built around psychology: train your discipline trade by trade until you execute like a machine. The results come after.',
  'Journal Trading · Dominá tu mente. Dominá tu trading.': 'Journal Trading · Master your mind. Master your trading.',
  'El journal de trading enfocado en la psicología: entrená tu disciplina trade por trade. Probalo gratis 7 días.': 'The trading journal built around psychology: train your discipline trade by trade. Try it free for 7 days.',
  'El journal de trading enfocado en la psicología: entrená tu disciplina trade por trade.': 'The trading journal built around psychology: train your discipline trade by trade.',
  'El método': 'The method',
  'Preguntas': 'FAQ',
  'Preguntas frecuentes': 'FAQ',
  'Planes': 'Pricing',
  'Iniciar sesión': 'Log in',
  'Ir a mi journal': 'Go to my journal',
  'Abrir menú': 'Open menu',
  'Cerrar menú': 'Close menu',
  'Dominá tu mente.': 'Master your mind.',
  'Dominá tu trading.': 'Master your trading.',
  'El FOMO, la venganza después de un stop, arriesgar de más: eso es lo que vacía las cuentas. Journal Trading está hecho para entrenar tu psicología trade por trade, hasta que operar tu plan sea automático. Los resultados llegan después.': 'FOMO, revenge after a stop-out, risking too much: that is what blows accounts. Journal Trading is built to train your psychology trade by trade, until following your plan becomes automatic. The results come after.',
  'Probar gratis 7 días': 'Try free for 7 days',
  'Ir directo a Pro': 'Go straight to Pro',
  'Sin tarjeta para la prueba gratis.': 'No card needed for the free trial.',
  'Probalo: registrá un trade': 'Try it: log a trade',
  'Demo: registrá un trade': 'Demo: log a trade',
  '¿Cumpliste tu Trading Plan?': 'Did you follow your Trading Plan?',
  'Entré en mi horario': 'Entered within my hours',
  'Bias definido antes de operar': 'Bias set before trading',
  'Respeté mi riesgo máximo': 'Respected my max risk',
  'No fue FOMO': "It wasn't FOMO",
  'FOMO': 'FOMO',
  'Tus últimos trades': 'Your latest trades',
  'Real': 'Actual',
  'Esto, pero con tus trades reales → Probar gratis 7 días': 'This, but with your real trades → Try free for 7 days',
  'Racha: 1 trade': 'Streak: 1 trade',
  'Racha: {n} trades': 'Streak: {n} trades',
  'Curva real contra curva con el plan': 'Actual curve vs. curve with the plan',
  'Romper el plan te costó <b>{cost}</b> · real {real}, con tu plan {plan}': 'Breaking the plan cost you <b>{cost}</b> · actual {real}, with your plan {plan}',
  'Los trades fuera de plan sumaron <b>{v}</b>, pero no son repetibles: un sistema que se rompe no se puede medir.': "Off-plan trades added <b>{v}</b>, but they aren't repeatable: a system you break can't be measured.",
  'Romper el plan no cambió el resultado: real {real}, con tu plan {plan}': "Breaking the plan didn't change the result: actual {real}, with your plan {plan}",
  'Elegí cómo te sentías al entrar.': 'Pick how you felt when you entered.',
  'Elegí el resultado del trade.': 'Pick the trade result.',
  'Trade de manual': 'Textbook trade',
  'Perdiste, pero bien': 'A loss, but a good one',
  'Plan cumplido y cabeza tranquila. Tu racha sube a {n}.': 'Plan followed with a calm head. Your streak goes up to {n}.',
  'Ejecutaste tu plan con la cabeza fría: las pérdidas dentro del plan son parte del sistema. Racha: {n}.': 'You executed your plan with a cool head: losses within the plan are part of the system. Streak: {n}.',
  'Plan cumplido, cabeza en riesgo': 'Plan followed, mindset at risk',
  'Respetaste las reglas, pero entraste con {emo}. Ese estado suele terminar rompiendo el plan en el próximo trade.': 'You followed the rules, but entered with {emo}. That state usually ends up breaking the plan on the next trade.',
  'Ganaste, pero rompiste el plan': 'You won, but broke the plan',
  'Faltó: {miss}.': 'Missing: {miss}.',
  'Faltó: {miss} y entraste con {emo}.': 'Missing: {miss}, and you entered with {emo}.',
  'Ese trade no es repetible: la racha vuelve a 0.': "That trade isn't repeatable: your streak resets to 0.",
  'Este es el trade que vacía cuentas': 'This is the trade that blows accounts',
  'Rompiste el plan ({miss}) con {emo} y perdiste.': 'You broke the plan ({miss}) with {emo} and lost.',
  'Rompiste el plan ({miss}) y perdiste.': 'You broke the plan ({miss}) and lost.',
  'La racha vuelve a 0.': 'Your streak resets to 0.',
  '“Un trader disciplinado con una estrategia promedio le gana a un trader impulsivo con la mejor estrategia del mundo.”': '“A disciplined trader with an average strategy beats an impulsive trader with the best strategy in the world.”',
  'Por eso no medimos solo tu PnL. Medimos si fuiste el trader que dijiste que ibas a ser.': "That's why we don't just measure your PnL. We measure whether you were the trader you said you'd be.",
  'Lo que nos diferencia': 'What makes us different',
  'La mayoría de los journals te muestran cuánto ganaste. Nosotros te mostramos por qué.': 'Most journals show you how much you made. We show you why.',
  'Un journal típico': 'A typical journal',
  'Gira alrededor del PnL': 'Revolves around PnL',
  'Un trade ganador es un buen trade': 'A winning trade is a good trade',
  'Registrás después y te olvidás': 'You log it later and forget it',
  'Te dice qué pasó': 'Tells you what happened',
  'Gira alrededor de tu comportamiento': 'Revolves around your behavior',
  'Un buen trade es el que respetó tu plan, gane o pierda': 'A good trade is one that followed your plan, win or lose',
  'Cada trade pasa por tu Trading Plan, con honestidad': 'Every trade goes through your Trading Plan, honestly',
  'Te muestra qué te cuesta romper tus reglas': 'Shows you what breaking your rules costs you',
  'El método: primero la mente, después los resultados': 'The method: mindset first, results follow',
  'Tres pasos que repetís en cada trade hasta que operar tu plan sea automático.': 'Three steps you repeat on every trade until following your plan becomes automatic.',
  'Escribí tus reglas': 'Write your rules',
  'Armá tu Trading Plan con las condiciones de tu estrategia. Son tus reglas, no las de otro, y quedan por escrito antes de operar.': "Build your Trading Plan with your strategy's conditions. They're your rules, not someone else's, and they're written down before you trade.",
  'Sé honesto en cada trade': 'Be honest on every trade',
  'Tildá solo lo que realmente se cumplió. Preguntas como “¿lo hubieras tomado sin ver los últimos 2 minutos?” sacan el FOMO a la luz.': 'Check only what was really met. Questions like “would you have taken it without watching the last 2 minutes?” bring FOMO to light.',
  'Medí tu disciplina': 'Measure your discipline',
  'Tu racha, tu % de plan seguido y la comparación plan seguido vs. plan roto te muestran en números cuánto te cuesta la impulsividad.': 'Your streak, your % of plan followed and the plan followed vs. plan broken comparison show you in numbers how much impulsiveness costs you.',
  '→ Cuando la disciplina se vuelve hábito, los resultados llegan solos.': '→ When discipline becomes a habit, the results follow.',
  'Herramientas para entrenar tu disciplina': 'Tools to train your discipline',
  'Para traders retail y para cuentas de fondeo.': 'For retail traders and funded accounts.',
  'Cada trade se valida contra tus reglas. Si faltó algo, queda registrado como plan roto, aunque haya salido bien.': 'Every trade is checked against your rules. If something was missing, it is logged as a broken plan, even if it worked out.',
  'Racha de disciplina': 'Discipline streak',
  'Contá cuántos trades seguidos respetaste tu plan. Romperla duele, y eso es lo que te frena antes del próximo impulso.': 'Count how many trades in a row you followed your plan. Breaking it hurts, and that is what stops you before the next impulse.',
  'Compará tus resultados cuando seguís el plan y cuando no. Ver el costo real de la impulsividad cambia cómo operás.': "Compare your results when you follow the plan and when you don't. Seeing the real cost of impulsiveness changes how you trade.",
  'Freno al sobre-riesgo': 'A brake on overrisking',
  'Definí tu riesgo máximo por día y mirá cuánto te queda. Se acabó el “un trade más para recuperar”.': 'Set your max risk per day and see how much you have left. No more “one more trade to win it back”.',
  'Cuentas de fondeo bajo control': 'Funded accounts under control',
  'Drawdown diario, total (estático o trailing) y profit target a la vista, para operar sin presión de más.': 'Daily drawdown, max drawdown (static or trailing) and profit target in view, so you trade without extra pressure.',
  'Calendario de disciplina': 'Discipline calendar',
  'Tu cumplimiento del plan día por día y semana por semana, al lado de tu PnL. Detectá los días en que te gana la emoción.': 'Your plan adherence day by day and week by week, next to your PnL. Spot the days when emotion gets the best of you.',
  'Lo que suelen preguntarnos antes de empezar.': 'What people usually ask us before getting started.',
  '¿Necesito tarjeta para la prueba gratis?': 'Do I need a card for the free trial?',
  'No. Creás tu cuenta y tenés 7 días con todas las funciones, sin cargar ningún medio de pago.': 'No. Create your account and get 7 days with every feature, without adding any payment method.',
  '¿Qué pasa cuando termina la prueba?': 'What happens when the trial ends?',
  'Para seguir registrando trades te pedimos pasar a Pro, mensual o anual. Todo lo que cargaste durante la prueba se mantiene.': 'To keep logging trades we ask you to upgrade to Pro, monthly or yearly. Everything you logged during the trial is kept.',
  '¿Puedo cancelar cuando quiera?': 'Can I cancel anytime?',
  'Sí. Podés cancelar en cualquier momento y seguís teniendo acceso hasta que termine el período que ya pagaste.': 'Yes. You can cancel at any time and keep access until the end of the period you already paid for.',
  '¿Sirve para cuentas de fondeo?': 'Does it work for funded accounts?',
  'Sí. Cargás las reglas de tu prop firm (drawdown diario, drawdown total estático o trailing y profit target) y ves en todo momento cuánto margen te queda.': "Yes. Enter your prop firm's rules (daily drawdown, static or trailing max drawdown and profit target) and always see how much room you have left.",
  '¿Sirve para mi estrategia y mi mercado?': 'Does it work for my strategy and market?',
  'Sí. El Trading Plan lo armás vos con tus propias reglas, así que funciona con cualquier estrategia y en cualquier mercado: futuros, forex, acciones o cripto.': 'Yes. You build the Trading Plan with your own rules, so it works with any strategy and any market: futures, forex, stocks or crypto.',
  '¿Dónde quedan mis datos?': 'Where is my data stored?',
  'Por ahora se guardan solo en el navegador que usás (no en un servidor), así que no se sincronizan entre dispositivos. Podés exportar una copia de seguridad cuando quieras desde Ajustes. Si compartís la computadora, cerrá sesión al terminar.': "For now it's stored only in the browser you use (not on a server), so it doesn't sync across devices. You can export a backup anytime from Settings. If you share the computer, log out when you're done.",
  'Elegí cómo empezar': 'Choose how to start',
  'Empezá a entrenar tu disciplina hoy. Probalo gratis o pasate a Pro desde el primer día.': 'Start training your discipline today. Try it free or go Pro from day one.',
  'USD 0': 'USD 0',
  '/ 7 días': '/ 7 days',
  'Todo Pro durante 7 días, sin tarjeta. Si después pasás a Pro, tus datos se mantienen.': 'All of Pro for 7 days, no card. If you upgrade to Pro afterwards, your data is kept.',
  'Tu Trading Plan, personalizado': 'Your own custom Trading Plan',
  'Racha y estadísticas de disciplina': 'Discipline streak and stats',
  'Calendarios de resultados y de cumplimiento': 'Results and adherence calendars',
  'Risk management diario': 'Daily risk management',
  'Seguimiento de cuentas de fondeo': 'Funded account tracking',
  'Backup de tus datos': 'Backup of your data',
  'Pro': 'Pro',
  'Recomendado': 'Recommended',
  'USD 14,99': 'USD 14.99',
  '/ mes': '/ month',
  '/ año': '/ year',
  'O pagá anual con un 20% de descuento.': 'Or pay yearly and get 20% off.',
  '<strong>20% de descuento pagando anual.</strong> Equivale a {perMonth}/mes: ahorrás {savings} al año.': '<strong>20% off when you pay yearly.</strong> That works out to {perMonth}/month: you save {savings} a year.',
  'Todo, sin límite de tiempo.': 'Everything, with no time limit.',
  'Ir a Pro': 'Go Pro',
  'Empezá a entrenar tu disciplina hoy.': 'Start training your discipline today.',
  '7 días gratis, sin tarjeta. Tu próximo trade puede ser el primero de tu racha.': '7 days free, no card. Your next trade could be the first of your streak.',
  'Ver planes': 'See pricing',
  'Forma de pago': 'Billing',

  // ---- Login y registro ----
  'Ingresar · Journal Trading': 'Log in · Journal Trading',
  'Volver al inicio': 'Back to home',
  'Crear cuenta': 'Sign up',
  'Continuar con Google': 'Continue with Google',
  'o con tu email': 'or with your email',
  '7 días, sin tarjeta': '7 days, no card',
  'Desde USD 11,99 / mes': 'From USD 11.99 / month',
  'Contraseña': 'Password',
  '¿Olvidaste tu contraseña?': 'Forgot your password?',
  'Mínimo 6 caracteres.': 'At least 6 characters.',
  '← Volver a iniciar sesión': '← Back to log in',
  'El journal que mide si fuiste el trader que dijiste que ibas a ser.': "The journal that measures whether you were the trader you said you'd be.",
  'Tu Trading Plan en cada trade': 'Your Trading Plan on every trade',
  'Risk management diario y cuentas de fondeo': 'Daily risk management and funded accounts',
  'Mostrar contraseña': 'Show password',
  'Ocultar contraseña': 'Hide password',
  'Qué bueno verte de nuevo': 'Good to see you again',
  'Ingresá para ir a tu journal.': 'Log in to go to your journal.',
  'Creá tu cuenta': 'Create your account',
  'Empezá tu prueba gratis de 7 días.': 'Start your 7-day free trial.',
  'Empezá con el plan Pro.': 'Start with the Pro plan.',
  'Recuperá tu contraseña': 'Reset your password',
  'Ingresá tu email y te mandamos un link para crear una contraseña nueva.': "Enter your email and we'll send you a link to create a new password.",
  'Enviar link': 'Send link',
  'Empezar prueba gratis': 'Start free trial',
  'Crear cuenta Pro anual': 'Create yearly Pro account',
  'Crear cuenta Pro mensual': 'Create monthly Pro account',
  'Pagando anual tenés un 20% de descuento: {price} / año.': 'Pay yearly and get 20% off: {price} / year.',
  'Al crear tu cuenta aceptás los <a href="terminos.html" target="_blank">Términos y condiciones</a> y la <a href="privacidad.html" target="_blank">Política de privacidad</a>.': 'By creating your account you accept the <a href="terminos.html" target="_blank">Terms and conditions</a> and the <a href="privacidad.html" target="_blank">Privacy policy</a>.',
  'El ingreso con Google se activa cuando conectemos el servidor. Por ahora usá tu email.': "Google sign-in will be enabled once we connect the server. For now, use your email.",
  'Ingresá tu nombre.': 'Enter your name.',
  'Ingresá tu email.': 'Enter your email.',
  'Ese email no parece válido.': "That email doesn't look valid.",
  'Ingresá un email válido.': 'Enter a valid email.',
  'Ingresá tu contraseña.': 'Enter your password.',
  'La contraseña tiene que tener al menos {n} caracteres.': 'Password must be at least {n} characters.',
  'Si hay una cuenta con ese email, te vamos a mandar un link para crear una contraseña nueva.': "If there's an account with that email, we'll send you a link to create a new password.",
  'El envío de emails se activa cuando conectemos el servidor.': 'Emails will be enabled once we connect the server.',
  'No se pudo guardar: el almacenamiento del navegador está lleno. Liberá espacio e intentá de nuevo.': "Couldn't save: browser storage is full. Free up space and try again.",
  'Ya existe una cuenta con ese email. Iniciá sesión.': 'An account with that email already exists. Log in.',
  'Email o contraseña incorrectos.': 'Wrong email or password.',

  // ---- Páginas legales ----
  'Términos y condiciones': 'Terms and conditions',
  'Términos y condiciones · Journal Trading': 'Terms and conditions · Journal Trading',
  'Política de privacidad': 'Privacy policy',
  'Política de privacidad · Journal Trading': 'Privacy policy · Journal Trading',
  'Estamos preparando este documento. Va a estar publicado acá antes del lanzamiento.': "We're preparing this document. It will be published here before launch.",

  // ---- Playbook ----
  'Playbook': 'Playbook',
  'Tu Playbook': 'Your Playbook',
  'Tus setups con sus criterios, un ejemplo y sus números reales. Los trades se vinculan por el nombre del setup.': 'Your setups with their criteria, an example and their real numbers. Trades are linked by setup name.',
  '+ Nuevo setup': '+ New setup',
  'Nuevo setup': 'New setup',
  'Editar setup': 'Edit setup',
  'Mejor setup': 'Best setup',
  'Te cuesta plata': 'Costing you money',
  'Armá tu Playbook': 'Build your Playbook',
  'Cada setup que operás, con sus criterios y una captura de ejemplo. Así ves cuál te da plata y cuál no, y lo repasás antes de entrar.': "Every setup you trade, with its criteria and an example screenshot. See which ones make you money and which don't, and review them before entering.",
  'Setups sin ficha': 'Setups without a card',
  'Los cargaste en tus trades pero todavía no están en tu Playbook.': "You've used them in your trades but they're not in your Playbook yet.",
  'Setup archivado': 'Archived setup',
  '1 setup archivado': '1 archived setup',
  '{n} setups archivados': '{n} archived setups',
  '{n} criterio': '{n} criterion',
  '{n} criterios': '{n} criteria',
  'Ejemplo del setup': 'Setup example',
  'Criterios para entrar': 'Entry criteria',
  'Todavía no cargaste criterios.': "You haven't added criteria yet.",
  'Tus números con este setup': 'Your numbers with this setup',
  'R promedio': 'Avg R',
  'Profit factor': 'Profit factor',
  'Prom. con plan': 'Avg with plan',
  'Todavía no hay trades con este setup. Cuando cargues uno, escribí "{name}" en el campo Setup.': 'No trades with this setup yet. When you log one, type "{name}" in the Setup field.',
  'Reactivar': 'Restore',
  'Archivar': 'Archive',
  'Nombre del setup': 'Setup name',
  'Es el mismo nombre que escribís en el campo Setup de cada trade.': "It's the same name you type in the Setup field of each trade.",
  'Descripción': 'Description',
  'Ej. Barrida de un máximo o mínimo previo y entrada en el FVG que queda después.': 'E.g. Sweep of a previous high or low and entry on the FVG left behind.',
  'Escribí un criterio': 'Write a criterion',
  'Quitar criterio': 'Remove criterion',
  'Sumá lo que tiene que pasar para que tomes este setup (ej. "Barrida de liquidez en zona de 4H").': 'Add what has to happen for you to take this setup (e.g. "Liquidity sweep at a 4H level").',
  'Podés cargar hasta 15 criterios.': 'You can add up to 15 criteria.',
  'Captura de ejemplo': 'Example screenshot',
  'Subí una captura de un ejemplo de manual': 'Upload a screenshot of a textbook example',
  'Poné un nombre al setup.': 'Give the setup a name.',
  'Ya tenés un setup con ese nombre.': 'You already have a setup with that name.',
  '¿Cambiar también el setup de 1 trade de "{old}" a "{name}"?': 'Also change the setup of 1 trade from "{old}" to "{name}"?',
  '¿Cambiar también el setup de los {n} trades de "{old}" a "{name}"?': 'Also change the setup of the {n} trades from "{old}" to "{name}"?',
  '¿Eliminar la ficha de "{name}"?': 'Delete the "{name}" card?',
  '¿Eliminar la ficha de "{name}"? El trade que lo usa conserva el nombre del setup.': 'Delete the "{name}" card? The trade that uses it keeps the setup name.',
  '¿Eliminar la ficha de "{name}"? Los {n} trades que lo usan conservan el nombre del setup.': 'Delete the "{name}" card? The {n} trades that use it keep the setup name.',
  'Ver ejemplo': 'See example',
  'Este setup no tiene criterios cargados.': "This setup doesn't have criteria yet.",
  'Trading Plan': 'Trading Plan',
  'Dos partes: las reglas generales, que cumplís en todos los trades, y tus setups, cada uno con sus criterios de entrada. Al registrar un trade tildás las reglas y los criterios del setup que operaste, y con eso se mide si respetaste el plan.': 'Two parts: the general rules, which apply to every trade, and your setups, each with its own entry criteria. When you log a trade you check the rules and the criteria of the setup you traded, and that is how following the plan is measured.',
  'Reglas generales': 'General rules',
  'Valen para todos tus trades, sin importar el setup: riesgo, horario, cuántas pérdidas por día. Ordenalas como las revisás.': 'They apply to every trade, whatever the setup: risk, trading hours, how many losses per day. Order them the way you check them.',
  'Riesgo máximo por día': 'Max risk per day',
  'Tus setups': 'Your setups',
  'Lo que tiene que pasar para entrar en cada setup, con un ejemplo y sus números reales. Los trades se vinculan por el nombre del setup.': 'What has to happen to enter each setup, with an example and its real numbers. Trades are linked by setup name.',
  'Elegí el setup y tocá cada regla y criterio que cumpliste': 'Pick the setup and tap each rule and criterion you followed',
  'Cumpliste <b>{done}/{total}</b> reglas y criterios': 'You followed <b>{done}/{total}</b> rules and criteria',
  'Criterios de {name}': '{name} criteria',
  '"{name}" no tiene ficha en tu plan, así que no suma criterios.': '"{name}" has no card in your plan, so it adds no criteria.',
  'Crear setup': 'Create setup',
  '· cuántas veces los cumpliste': '· how often you met them',
  'No marcaste ninguna regla ni criterio de tu Trading Plan. Si guardás así, el trade queda como "Plan roto". ¿Guardar igual?': 'You didn\'t check any rule or criterion from your Trading Plan. If you save like this, the trade is marked "Plan broken". Save anyway?',
  'Borra todos tus trades, rachas y meses cerrados. Tu plan, tus setups y tus ajustes se mantienen.': 'Deletes all your trades, streaks and closed months. Your plan, setups and settings are kept.',
  'Las reglas generales y los setups que operás.': 'Your general rules and the setups you trade.',
  'Ir a Plan': 'Go to Plan',
  'Armá tu Trading Plan en la pestaña Plan para ver qué reglas cumplís más.': 'Build your Trading Plan in the Plan tab to see which rules you follow most.',
  'Reglas y criterios que faltaron': 'Missed rules and criteria',

  // ---- Filtros de Estadísticas ----
  'Rango': 'Range',
  'Rango de fechas': 'Date range',
  'Desde': 'From',
  'Hasta': 'To',
  'Elegí las dos fechas.': 'Pick both dates.',
  'La fecha de inicio tiene que ser anterior a la de fin.': 'The start date must be before the end date.',
  'Filtrar': 'Filter',
  'Quitar filtro': 'Remove filter',
  '1 filtro': '1 filter',
  '{n} filtros': '{n} filters',
  'Día': 'Day',
  'Tocá para filtrar por esto': 'Tap to filter by this',

  // ---- App instalable ----
  'App en tu dispositivo': 'App on your device',
  'Instalá Journal Trading como una app: abre desde el inicio de tu celular o tu compu, en pantalla completa y sin conexión.': 'Install Journal Trading as an app: open it from your phone or computer home screen, full screen and offline.',
  'Instalar la app': 'Install the app',
  'Instalar la app en este dispositivo': 'Install the app on this device',
  'Ya estás usando la app instalada.': "You're using the installed app.",
  'Funciona sin conexión: tus datos se guardan en este dispositivo.': 'Works offline: your data is stored on this device.',
  'Abrí esta página en Safari.': 'Open this page in Safari.',
  'Tocá el botón Compartir (el cuadrado con la flecha).': 'Tap the Share button (the square with the arrow).',
  'Elegí "Agregar a inicio".': 'Choose "Add to Home Screen".',
  'Tu navegador no ofrece instalarla desde acá. En Chrome o Edge buscá "Instalar app" en el menú o en la barra de direcciones; en iPhone, usá Safari → Compartir → Agregar a inicio.': 'Your browser doesn\'t offer installing it from here. In Chrome or Edge look for "Install app" in the menu or the address bar; on iPhone, use Safari → Share → Add to Home Screen.',
  'Hay una versión nueva de la app.': 'A new version of the app is available.',
  'Actualizar': 'Update',
  'Sin conexión. Podés seguir usando el journal: tus datos se guardan en este dispositivo.': "You're offline. You can keep using the journal: your data is stored on this device.",

  // ---- Compartir y reporte mensual ----
  'Compartir': 'Share',
  'Compartir trade': 'Share trade',
  'Compartir mes': 'Share month',
  'Mi mes': 'My month',
  'Mejor racha': 'Best streak',
  'Resultado en la imagen': 'Result in the image',
  'En %': 'In %',
  'En R': 'In R',
  'Nunca se muestran montos en dinero.': 'Money amounts are never shown.',
  'Descargar imagen': 'Download image',
  'No se pudo compartir. Descargá la imagen y subila a mano.': "Couldn't share. Download the image and upload it manually.",
  'Reporte PDF': 'PDF report',
  'Reporte': 'Report',
  'Reporte mensual': 'Monthly report',
  'Generado el {date}': 'Generated on {date}',
  'meta {goal}%': 'goal {goal}%',
  'Con tu plan habrías hecho {plan}': 'With your plan you would have made {plan}',
  'Por setup': 'By setup',
  'Por sesión': 'By session',
  'Por emoción': 'By emotion',
  'Veces': 'Times',
  'Revisiones semanales': 'Weekly reviews',
  'Disciplina {n}/10': 'Discipline {n}/10',
  'Trades del mes': "Month's trades",
  'No hay trades en este mes.': 'No trades this month.',
};
