// Traducción al inglés. Clave: el texto original en español, tal cual aparece
// en el código o en el HTML. Ver js/i18n.js.
const I18N_EN = {
  // ---- Marco de la app y navegación ----
  'Mi journal · Journal Trading': 'My journal · Journal Trading',
  'Journal Trading': 'Journal Trading',
  'Inicio': 'Home',
  'curva|Inicio': 'Start',
  'Trade': 'Trade',
  'Stats': 'Stats',
  'Estadísticas': 'Statistics',
  'Calendario': 'Calendar',
  'Historial': 'History',
  'Revisión': 'Review',
  'Revisión semanal': 'Weekly review',
  'Ajustes': 'Settings',
  'Cerrar sesión': 'Log out',
  'Salir': 'Log out',
  'No soy yo · Cerrar sesión': 'Not me · Log out',
  'Cerrar': 'Close',
  'Cuenta que estás viendo': 'Account you are viewing',
  'Cambiar a modo claro': 'Switch to light mode',
  'Cambiar a modo oscuro': 'Switch to dark mode',
  'Guardado': 'Saved',

  // ---- Plan y prueba ----
  'Pro · anual': 'Pro · yearly',
  'Pro · mensual': 'Pro · monthly',
  'Prueba gratis': 'Free trial',
  'Prueba terminada': 'Trial ended',
  'queda 1 día': '1 day left',
  'quedan {n} días': '{n} days left',
  'por año · {price}/mes': 'per year · {price}/month',
  'Tu prueba gratis terminó': 'Your free trial has ended',
  'Pasate a Pro': 'Upgrade to Pro',
  'Pasar a Pro': 'Upgrade to Pro',
  'Pasate a Pro para seguir registrando trades. Tus datos siguen guardados.': 'Upgrade to Pro to keep logging trades. Your data is still saved.',
  'Seguí entrenando tu disciplina sin límite de tiempo.': 'Keep training your discipline with no time limit.',
  '¡Listo, ya sos Pro!': "Done, you're Pro now!",
  'Seguí registrando tus trades sin límite.': 'Keep logging your trades with no limits.',
  'Mensual': 'Monthly',
  'por mes': 'per month',
  'Anual': 'Yearly',
  '20% de descuento pagando anual.': '20% off when you pay yearly.',
  'Ahora no': 'Not now',
  'Descargar mis datos': 'Download my data',
  'Tu plan': 'Your plan',
  'anual': 'yearly',
  'mensual': 'monthly',
  '/año': '/year',
  '/mes': '/month',
  'Miembro desde {since}.': 'Member since {since}.',
  'Te queda 1 día de prueba.': 'You have 1 trial day left.',
  'Te quedan {n} días de prueba.': 'You have {n} trial days left.',
  'Tu prueba terminó.': 'Your trial has ended.',

  // ---- Inicio (texto fijo) ----
  'Revisar semana': 'Review week',
  'Ver stats': 'See stats',
  'Tu día de hoy': 'Your day today',
  'Meta del mes': 'Monthly goal',
  'Cambiar meta →': 'Change goal →',
  'Cuánto margen te queda según las reglas de tu prop firm.': 'How much room you have left under your prop firm rules.',
  'Tu semana': 'Your week',
  'Calendario →': 'Calendar →',
  'Últimos trades': 'Latest trades',
  'Historial →': 'History →',
  'Lo que dicen tus datos': 'What your data says',
  'Ver todos →': 'See all →',
  'Logros': 'Achievements',

  // ---- Registrar trade ----
  'Registrar trade': 'Log trade',
  'Editar trade': 'Edit trade',
  'Agregar trade': 'Add trade',
  'Guardar cambios': 'Save changes',
  'Cancelar edición': 'Cancel editing',
  'Paso 1 de 4': 'Step 1 of 4',
  'Paso 2 de 4': 'Step 2 of 4',
  'Paso 3 de 4': 'Step 3 of 4',
  'Paso 4 de 4': 'Step 4 of 4',
  '{n} de 4 secciones completas': '{n} of 4 sections complete',
  'Tu Trading Plan': 'Your Trading Plan',
  'Tocá cada regla que cumpliste': 'Tap each rule you followed',
  'Todavía no armaste tu Trading Plan. Cargá las reglas que tiene que cumplir cada trade y acá vas a poder tildarlas.': "You haven't built your Trading Plan yet. Add the rules every trade must follow and you'll be able to check them off here.",
  'Armar mi Trading Plan': 'Build my Trading Plan',
  'Cumpliste <b>{done}/{total}</b> reglas': 'You followed <b>{done}/{total}</b> rules',
  'Dentro del plan': 'Within plan',
  'Fuera del plan': 'Off plan',
  'Sin marcar': 'Not checked',
  'El trade': 'The trade',
  'Qué operaste y cómo salió': 'What you traded and how it went',
  'Cuenta': 'Account',
  'Resultado': 'Result',
  'Ganador': 'Winner',
  'Perdedor': 'Loser',
  'Break even': 'Break even',
  'TP': 'TP',
  'SL': 'SL',
  'BE': 'BE',
  'Dirección': 'Direction',
  'Long': 'Long',
  'Short': 'Short',
  'Activo': 'Asset',
  'Ej. NQ, EURUSD': 'E.g. NQ, EURUSD',
  'Fecha y hora de entrada': 'Entry date and time',
  'hora de Nueva York': 'New York time',
  'tu hora local': 'your local time',
  'Sesión: {s}': 'Session: {s}',
  'Cuenta para el día {d}': 'Counts for {d}',
  '{time} tu hora': '{time} your time',
  'Setup': 'Setup',
  'Ej. Sweep + IFVG': 'E.g. Sweep + IFVG',
  'Riesgo (%)': 'Risk (%)',
  'Ej. 0.5': 'E.g. 0.5',
  'R:R planeado': 'Planned R:R',
  'Ej. 2 (para 1:2)': 'E.g. 2 (for 1:2)',
  'Resultado real (%)': 'Actual result (%)',
  'Ej. 1.2 o -0.5': 'E.g. 1.2 or -0.5',
  'R real': 'Actual R',
  'R real: {r}': 'Actual R: {r}',
  'Duración (minutos)': 'Duration (minutes)',
  'Ej. 12': 'E.g. 12',
  'Tu cabeza': 'Your mindset',
  'Cómo estabas cuando entraste': 'How you felt when you entered',
  '¿Cómo te sentías al entrar?': 'How did you feel when you entered?',
  'Estados que ayudan': 'Helpful states',
  'Estados de riesgo': 'Risky states',
  'Tranquilo': 'Calm',
  'Confiado': 'Confident',
  'Ansioso': 'Anxious',
  'Revancha': 'Revenge',
  'Aburrido': 'Bored',
  'Nivel de confianza en el trade': 'Confidence in the trade',
  'Confianza 1': 'Confidence 1',
  'Confianza 2': 'Confidence 2',
  'Confianza 3': 'Confidence 3',
  'Confianza 4': 'Confidence 4',
  'Confianza 5': 'Confidence 5',
  'Nada seguro': 'Not sure at all',
  'Poco seguro': 'Slightly sure',
  'Neutral': 'Neutral',
  'Bastante seguro': 'Fairly sure',
  'Totalmente seguro': 'Completely sure',
  '¿Cometiste algún error?': 'Did you make any mistakes?',
  '(podés marcar varios)': '(you can pick several)',
  'Moví el stop': 'Moved my stop',
  'Cerré antes de tiempo': 'Closed too early',
  'Entré tarde': 'Entered late',
  'Entré sin confirmación': 'Entered without confirmation',
  'Sobreoperé': 'Overtraded',
  'Aumenté el tamaño': 'Sized up',
  'No respeté el TP': "Didn't respect my TP",
  'Notas': 'Notes',
  'Lo que querés recordar de este trade': 'What you want to remember about this trade',
  '¿Qué pasó en el desarrollo del trade?': 'What happened during the trade?',
  '(opcional)': '(optional)',
  'Ej. Esperé la confirmación, pero cerré antes por miedo a que volviera.': 'E.g. I waited for confirmation, but closed early out of fear it would reverse.',
  'Arrastrá la imagen acá o': 'Drag the image here or',
  'elegí un archivo': 'choose a file',
  'PNG o JPG · también podés pegarla con Ctrl+V': 'PNG or JPG · you can also paste it with Ctrl+V',
  'Captura del trade': 'Trade screenshot',
  'Cambiar': 'Change',
  'Quitar': 'Remove',
  'Vista previa': 'Preview',
  'Completá el formulario y el trade se arma acá.': 'Fill in the form and your trade takes shape here.',
  'Plan respetado': 'Plan followed',
  'Sí': 'Yes',
  'No': 'No',
  'Emoción': 'Emotion',
  'Errores': 'Mistakes',
  'Puntaje de disciplina': 'Discipline score',
  'Completá el formulario para ver tu puntaje.': 'Fill in the form to see your score.',
  'Trade ejecutado con disciplina.': 'Trade executed with discipline.',
  'Hay cosas para ajustar.': 'Some things to adjust.',
  'Este trade se alejó de tu plan.': 'This trade drifted from your plan.',
  'El riesgo tiene que ser un número (ej. 0.5).': 'Risk must be a number (e.g. 0.5).',
  'El riesgo tiene que ser mayor a 0 y como máximo 100%.': 'Risk must be greater than 0 and at most 100%.',
  'El R:R planeado tiene que ser un número (ej. 2).': 'Planned R:R must be a number (e.g. 2).',
  'El R:R planeado tiene que ser mayor a 0 (ej. 2 para 1:2).': 'Planned R:R must be greater than 0 (e.g. 2 for 1:2).',
  'La duración tiene que ser un número de minutos (ej. 12).': 'Duration must be a number of minutes (e.g. 12).',
  'La duración no puede ser negativa.': "Duration can't be negative.",
  'Elegí un resultado (Ganador, Perdedor o Break even) antes de registrar.': 'Pick a result (Winner, Loser or Break even) before logging.',
  'El resultado tiene que ser un número (ej. 1.2 o -0.5).': 'Result must be a number (e.g. 1.2 or -0.5).',
  'Revisá el resultado: no puede ser mayor a 100% ni menor a -100%.': "Check the result: it can't be above 100% or below -100%.",
  'Marcaste Ganador pero el resultado es negativo. Revisá el resultado o elegí Perdedor.': 'You picked Winner but the result is negative. Check the result or pick Loser.',
  'Marcaste Perdedor pero el resultado es positivo. Revisá el resultado o elegí Ganador.': 'You picked Loser but the result is positive. Check the result or pick Winner.',
  'Revisá la fecha y hora de entrada.': 'Check the entry date and time.',
  'La fecha de entrada no puede ser futura.': "The entry date can't be in the future.",
  'Ese trade ya no existe (se eliminó). No se guardaron los cambios.': 'That trade no longer exists (it was deleted). Your changes were not saved.',
  'No marcaste ninguna regla de tu Trading Plan. Si guardás así, el trade queda como "Plan roto". ¿Guardar igual?': 'You didn\'t check any rule from your Trading Plan. If you save like this, the trade is marked "Plan broken". Save anyway?',
  'No se pudo guardar el trade porque el almacenamiento del navegador está lleno. Exportá un backup y liberá espacio.': "The trade couldn't be saved because browser storage is full. Export a backup and free up space.",

  // ---- Estadísticas, historial y revisión (texto fijo) ----
  'Período': 'Period',
  'Esta semana': 'This week',
  'Este mes': 'This month',
  '3 meses': '3 months',
  'Todo': 'All',
  'Disciplina': 'Discipline',
  'Trades con tu plan respetado contra tu meta.': 'Trades that followed your plan vs. your goal.',
  'Curva de resultados': 'Equity curve',
  'Resultado real': 'Actual result',
  'Si hubieras seguido tu plan': 'If you had followed your plan',
  'Lo que te costó romperlo': 'What breaking it cost you',
  'Plan roto': 'Plan broken',
  'Plan seguido': 'Plan followed',
  'Patrones que aparecen en tus trades del período.': 'Patterns showing up in your trades for this period.',
  'Mapa de calor: cuándo rompés el plan': 'Heatmap: when you break your plan',
  'Cada celda es un día y una hora de entrada, en hora de Nueva York. Pasá el mouse para ver el detalle.': 'Each cell is an entry day and hour, in New York time. Hover to see the details.',
  'El número es la cantidad de trades': 'The number is the trade count',
  'Desglose': 'Breakdown',
  'Sesión': 'Session',
  'Plan seguido vs. plan roto': 'Plan followed vs. plan broken',
  'Lo mismo medido de los dos lados.': 'The same metrics on both sides.',
  'Qué regla cumplís más': 'Which rules you follow most',
  'Porcentaje de trades en los que tildaste cada regla.': 'Share of trades where you checked each rule.',
  'Cierre mensual': 'Monthly close',
  'Cada mes se cierra solo al terminar. Siempre muestra todo tu historial.': 'Each month closes automatically when it ends. It always shows your full history.',
  'Hoy': 'Today',
  'Mes': 'Month',
  'Año': 'Year',
  'Anterior': 'Previous',
  'Buscar por activo, setup o nota': 'Search by asset, setup or note',
  'Buscar trades': 'Search trades',
  'Ordenar': 'Sort',
  'Más recientes': 'Newest',
  'Más antiguos': 'Oldest',
  'Mejor resultado': 'Best result',
  'Peor resultado': 'Worst result',
  'Mayor riesgo': 'Highest risk',
  'Ganadores': 'Winners',
  'Perdedores': 'Losers',
  'Con errores': 'With mistakes',
  'Con captura': 'With screenshot',
  'Por completar': 'To complete',
  'Semana anterior': 'Previous week',
  'Semana siguiente': 'Next week',
  'Resultado por día': 'Result by day',
  'Trades de la semana': "This week's trades",
  'Revisión guiada': 'Guided review',
  'Cinco minutos al final de la semana para mirar cómo operaste, no solo cuánto ganaste.': 'Five minutes at the end of the week to look at how you traded, not just how much you made.',
  'Lo que hiciste bien': 'What you did well',
  '¿Qué hiciste bien esta semana?': 'What did you do well this week?',
  'Ej. Esperé la confirmación en todos los trades y respeté el horario.': 'E.g. I waited for confirmation on every trade and stuck to my hours.',
  'El error que se repitió': 'The mistake that repeated',
  '¿Qué error se repitió y por qué creés que pasó?': 'Which mistake repeated and why do you think it happened?',
  'Ej. Cerré antes de tiempo dos veces por miedo a devolver la ganancia.': 'E.g. I closed early twice out of fear of giving back profit.',
  'Qué vas a cambiar': "What you'll change",
  '¿Qué vas a hacer distinto la semana que viene?': 'What will you do differently next week?',
  '(va a ser tu compromiso)': "(it'll be your commitment)",
  'Ej. Dejar correr el trade hasta el TP salvo que se invalide el setup.': 'E.g. Let the trade run to TP unless the setup is invalidated.',
  'Del 1 al 10, ¿cómo calificás tu disciplina esta semana?': 'From 1 to 10, how would you rate your discipline this week?',
  'Guardar revisión': 'Save review',
  'Revisiones anteriores': 'Past reviews',
  'Cómo evoluciona tu nota de disciplina semana a semana.': 'How your discipline score evolves week by week.',
  '+ Registrar trade en este día': '+ Log a trade on this day',

  // ---- Ajustes ----
  'Perfil': 'Profile',
  'Cómo te ves en la app y en qué plan estás.': 'How you appear in the app and which plan you are on.',
  'Nombre': 'Name',
  'Email': 'Email',
  'Color del avatar': 'Avatar color',
  'Color por defecto': 'Default color',
  'Color {c}': 'Color {c}',
  'Idioma · Language': 'Language · Idioma',
  'Metas y riesgo': 'Goals and risk',
  'Los límites que te ponés para operar con disciplina.': 'The limits you set to trade with discipline.',
  'Meta del mes: trades con el plan respetado': 'Monthly goal: trades that followed the plan',
  'Ej. 80': 'E.g. 80',
  'Meta personalizada': 'Custom goal',
  'Todavía no registraste trades este mes. La meta es que el <b>{goal}%</b> respete tu plan.': "You haven't logged trades this month yet. The goal is for <b>{goal}%</b> to follow your plan.",
  'Este mes vas <b>{pct}%</b> ({done}/{n})': 'This month you are at <b>{pct}%</b> ({done}/{n})',
  'Vas cumpliendo la meta. Mantenela hasta fin de mes.': "You're on track. Keep it up until the end of the month.",
  'Este mes ya no se puede llegar al 100%.': "100% is no longer reachable this month.",
  'Te falta <b>1</b> trade seguido respetando el plan para llegar.': 'You need <b>1</b> more trade in a row following the plan to get there.',
  'Te faltan <b>{n}</b> trades seguidos respetando el plan para llegar.': 'You need <b>{n}</b> trades in a row following the plan to get there.',
  'Riesgo máximo por día según tu Trading Plan': 'Max risk per day according to your Trading Plan',
  'Ej. 1': 'E.g. 1',
  'Riesgo personalizado': 'Custom risk',
  'Elegí tu riesgo máximo diario para ver cuánto te queda cada día.': 'Set your max daily risk to see how much you have left each day.',
  'Riesgo tomado hoy': 'Risk taken today',
  'Límite superado': 'Limit exceeded',
  'Límite alcanzado': 'Limit reached',
  'Cerca del límite': 'Close to the limit',
  'Dentro del límite': 'Within the limit',
  'Arriesgaste {used}% y tu máximo es {max}%. Hoy rompiste tu risk management.': 'You risked {used}% and your max is {max}%. You broke your risk management today.',
  'Ya usaste todo tu riesgo de hoy. Lo que sigue es fuera de plan.': "You've used all your risk for today. Anything else is off plan.",
  'Te quedan {n}% de riesgo para hoy.': 'You have {n}% risk left for today.',
  'Horarios': 'Time',
  'Las estadísticas, el calendario y las sesiones se calculan siempre en hora de Nueva York, la referencia del trading.': 'Statistics, the calendar and sessions are always calculated in New York time, the trading standard.',
  'Mostrar y cargar las horas en': 'Show and enter times in',
  'Hora de Nueva York': 'New York time',
  'Mi hora local': 'My local time',
  'Tu hora local coincide con la de Nueva York.': 'Your local time matches New York time.',
  'Ahora son las {ny} en Nueva York y las {local} en tu zona ({zone}).': "It's {ny} in New York and {local} in your time zone ({zone}).",
  'El día de trading termina a las': 'The trading day ends at',
  'Medianoche NY': 'NY midnight',
  '17:00 NY (forex y futuros)': '5:00 PM NY (forex and futures)',
  'Lo que operes desde las 17:00 de NY cuenta para el día siguiente, como el cierre de forex y futuros.': 'Anything you trade from 5:00 PM NY counts for the next day, like the forex and futures close.',
  'Cada día va de 00:00 a 23:59 en hora de Nueva York.': 'Each day runs from 00:00 to 23:59 New York time.',
  'Sesiones y killzones': 'Sessions and killzones',
  '(hora de Nueva York)': '(New York time)',
  'Nombre de la sesión': 'Session name',
  'Empieza (hora NY)': 'Starts (NY time)',
  'Termina (hora NY)': 'Ends (NY time)',
  'a': 'to',
  '{from} a {to} en tu hora': '{from} to {to} your time',
  'Eliminar sesión': 'Delete session',
  'Sin sesiones: todos los trades quedan "Fuera de sesión".': 'No sessions: every trade is "Outside session".',
  'Poné un nombre a la sesión.': 'Give the session a name.',
  'Completá la hora de inicio y de fin.': 'Fill in the start and end time.',
  'La sesión tiene que empezar y terminar a horas distintas.': 'The session must start and end at different times.',
  'Podés tener hasta 12 sesiones.': 'You can have up to 12 sessions.',
  'Nueva sesión': 'New session',
  '+ Agregar sesión': '+ Add session',
  '+ Killzones ICT': '+ ICT killzones',
  'Volver a las de siempre': 'Reset to defaults',
  '¿Volver a las sesiones de siempre (Asia, Londres y Nueva York)? Se borran las que agregaste.': 'Reset to the default sessions (Asia, London and New York)? The ones you added will be deleted.',
  'Cada trade toma la sesión de su hora de entrada. Si dos se superponen, cuenta la más corta (la killzone gana sobre la sesión entera). Los cambios se aplican también a los trades que ya cargaste.': 'Each trade takes the session of its entry time. If two overlap, the shorter one wins (a killzone wins over the full session). Changes also apply to trades you already logged.',
  'Asia': 'Asia',
  'Londres': 'London',
  'Nueva York': 'New York',
  'Fuera de sesión': 'Outside session',
  'Datos y backup': 'Data and backup',
  'Por ahora tus datos se guardan solo en este navegador. Exportá un backup para no perderlos o pasarlos a otro dispositivo.': 'For now your data is stored only in this browser. Export a backup so you don\'t lose it or to move it to another device.',
  'Exportar backup': 'Export backup',
  'Descargá un archivo con todos tus datos.': 'Download a file with all your data.',
  'Importar backup': 'Import backup',
  'Reemplazá tus datos por los de un archivo.': 'Replace your data with the data in a file.',
  'Importar trades (CSV)': 'Import trades (CSV)',
  'Traé tu historial desde cualquier broker o plataforma. Se suman a los que ya tenés.': 'Bring in your history from any broker or platform. They are added to the ones you already have.',
  'Esto reemplaza todos los datos actuales por los del backup ({n} trades{extra}). ¿Continuar?': 'This replaces all your current data with the backup ({n} trades{extra}). Continue?',
  '; {n} registros dañados se van a descartar': '; {n} damaged records will be discarded',
  'No se pudo leer el archivo.': "The file couldn't be read.",
  'No se pudieron leer tus datos guardados (el archivo está dañado). Se guardó una copia aparte; si tenés un backup, importalo desde Ajustes.': "Your saved data couldn't be read (the file is damaged). A copy was saved separately; if you have a backup, import it from Settings.",
  'No se pudo guardar: el almacenamiento del navegador está lleno. Exportá un backup y borrá trades viejos o imágenes.': "Couldn't save: browser storage is full. Export a backup and delete old trades or images.",
  'No se pudo guardar en el navegador. Exportá un backup desde Ajustes para no perder datos.': "Couldn't save in the browser. Export a backup from Settings so you don't lose data.",
  'Zona peligrosa': 'Danger zone',
  'Borra todos tus trades, rachas y meses cerrados. Tu Trading Plan y tus ajustes se mantienen.': 'Deletes all your trades, streaks and closed months. Your Trading Plan and settings are kept.',
  'Borrar todo el historial': 'Delete all history',
  '¿Seguro? Se borran todos tus trades y no se puede deshacer.': 'Are you sure? All your trades will be deleted and this cannot be undone.',
  'Sí, borrar todo': 'Yes, delete everything',
  'Las reglas que tiene que cumplir cada trade, en el orden en que las revisás.': 'The rules every trade must follow, in the order you check them.',
  'Escribí una nueva regla': 'Write a new rule',
  'Aclaración opcional (ej. 9:30 a 11:00 NY)': 'Optional note (e.g. 9:30 to 11:00 NY)',
  'Agregar': 'Add',
  '+ Agregar aclaración': '+ Add note',
  'Regla': 'Rule',
  'Aclaración (opcional)': 'Note (optional)',
  'Aclaración': 'Note',
  'Subir': 'Move up',
  'Bajar': 'Move down',
  'Editar': 'Edit',
  'Editar regla': 'Edit rule',
  'Eliminar regla': 'Delete rule',
  'Tu Trading Plan está vacío. Agregá la primera regla abajo.': 'Your Trading Plan is empty. Add your first rule below.',
  '¿Eliminar la regla "{rule}" de tu Trading Plan? Los trades que ya cargaste la siguen mostrando como estaba.': 'Delete the rule "{rule}" from your Trading Plan? Trades you already logged keep showing it as it was.',
  '{n} regla': '{n} rule',
  '{n} reglas': '{n} rules',
  'Guardar': 'Save',
  'Cancelar': 'Cancel',
  'Eliminar': 'Delete',
  'Eliminar…': 'Delete…',

  // ---- Cuentas ----
  'Cuentas': 'Accounts',
  'Tu cuenta personal, challenges y cuentas fondeadas, cada una con sus reglas.': 'Your personal account, challenges and funded accounts, each with its own rules.',
  '+ Agregar cuenta': '+ Add account',
  'Mi cuenta': 'My account',
  'Todas las cuentas': 'All accounts',
  '{n} cuenta': '{n} account',
  '{n} cuentas': '{n} accounts',
  '{n} trade': '{n} trade',
  '{n} trades': '{n} trades',
  'Personal': 'Personal',
  'Challenge': 'Challenge',
  'Fondeada': 'Funded',
  'Activa': 'Active',
  'Aprobada': 'Passed',
  'Quemada': 'Failed',
  'Archivada': 'Archived',
  'Cuenta de fondeo': 'Funded account',
  'Cuentas de fondeo': 'Funded accounts',
  'Crear fondeada': 'Create funded',
  '{name} fondeada': '{name} funded',
  'Editar cuenta': 'Edit account',
  'Nueva cuenta': 'New account',
  'Tipo': 'Type',
  'Tu propia cuenta, sin reglas de una prop firm.': 'Your own account, without prop firm rules.',
  'La evaluación de una prop firm: tenés que llegar al objetivo sin romper las reglas.': "A prop firm evaluation: you have to hit the target without breaking the rules.",
  'Cuenta ya fondeada: se cuidan los drawdowns, sin objetivo.': 'Already funded: protect the drawdowns, no target.',
  'Ej. Challenge 50K fase 1': 'E.g. 50K Challenge phase 1',
  'Ej. Mi cuenta': 'E.g. My account',
  'Prop firm': 'Prop firm',
  'Ej. tu prop firm': 'E.g. your prop firm',
  'Tamaño en USD (opcional)': 'Size in USD (optional)',
  'Ej. {v}': 'E.g. {v}',
  'Reglas': 'Rules',
  'Drawdown diario': 'Daily drawdown',
  'Drawdown máximo': 'Max drawdown',
  'Tipo de drawdown máximo': 'Max drawdown type',
  'Estático': 'Static',
  'Trailing': 'Trailing',
  'Profit target': 'Profit target',
  'Días mínimos (opcional)': 'Minimum days (optional)',
  'Consistencia': 'Consistency',
  'Consistencia (opcional)': 'Consistency (optional)',
  'El piso deja de subir cuando llega al balance inicial (mi firma congela el trailing)': 'The floor stops rising once it reaches the starting balance (my firm locks the trailing)',
  'La consistencia limita cuánto puede pesar tu mejor día sobre la ganancia total (ej. 30%: ningún día puede ser más del 30% del total).': 'Consistency limits how much your best day can weigh on total profit (e.g. 30%: no day can be more than 30% of the total).',
  'Estado': 'Status',
  'Poné un nombre para reconocer la cuenta.': 'Give the account a name you will recognize.',
  'El tamaño tiene que ser un número (ej. 50000).': 'Size must be a number (e.g. 50000).',
  'drawdown diario': 'daily drawdown',
  'drawdown máximo': 'max drawdown',
  'el drawdown diario': 'the daily drawdown',
  'el drawdown máximo': 'the max drawdown',
  'profit target': 'profit target',
  'consistencia': 'consistency',
  'Revisá el {rule}: tiene que ser un número entre 0 y 100.': 'Check the {rule}: it must be a number between 0 and 100.',
  'Los días mínimos tienen que ser un número entero (ej. 4).': 'Minimum days must be a whole number (e.g. 4).',
  'No se pudo guardar.': "Couldn't save.",
  '"{acc}" tiene 1 trade. Si la eliminás, pasa a "{other}". Si querés conservarlo aparte, mejor archivala (Estado → Archivada). ¿Eliminar igual?': '"{acc}" has 1 trade. If you delete it, it moves to "{other}". To keep it separate, archive the account instead (Status → Archived). Delete anyway?',
  '"{acc}" tiene {n} trades. Si la eliminás, pasan a "{other}". Si querés conservarlos aparte, mejor archivala (Estado → Archivada). ¿Eliminar igual?': '"{acc}" has {n} trades. If you delete it, they move to "{other}". To keep them separate, archive the account instead (Status → Archived). Delete anyway?',
  '{acc}: ya no te queda margen hasta {which}. Hoy no operes esta cuenta.': "{acc}: you have no room left before {which}. Don't trade this account today.",
  'Cuidado: arriesgás {risk}% y en {acc} te quedan {left}% hasta {which}.': 'Careful: you are risking {risk}% and {acc} only has {left}% left before {which}.',
  '{acc}: te quedan {left} hasta {which}.': '{acc}: {left} left before {which}.',
  'Regla rota': 'Rule broken',
  'Rompiste el {rule} el {date}. Si tu prop firm la dio por perdida, marcala como quemada.': 'You broke the {rule} on {date}. If your prop firm failed the account, mark it as failed.',
  'Objetivo cumplido': 'Target reached',
  'Cumpliste todas las reglas del challenge. Cuando tu firma lo confirme, marcala como aprobada.': 'You met every challenge rule. Once your firm confirms it, mark it as passed.',
  'Falta una regla': 'One rule missing',
  'Llegaste al objetivo pero te faltan días operados.': 'You hit the target but still need more trading days.',
  'Llegaste al objetivo pero tu mejor día pesa demasiado (regla de consistencia).': 'You hit the target but your best day weighs too much (consistency rule).',
  'En curso': 'In progress',
  'te quedan {left}': '{left} left',
  'límite alcanzado': 'limit reached',
  'Hoy: {pnl}': 'Today: {pnl}',
  '(trailing, se congela en el inicial)': '(trailing, locks at starting balance)',
  '(trailing)': '(trailing)',
  '(estático)': '(static)',
  'Pico: {v}': 'Peak: {v}',
  'Piso: {v}': 'Floor: {v}',
  'Acumulado: {v}': 'Total: {v}',
  'Objetivo alcanzado': 'Target reached',
  'Te falta {v}': '{v} to go',
  'Días operados': 'Trading days',
  'Mínimo cumplido': 'Minimum met',
  'Te falta 1 día con trades': '1 more trading day needed',
  'Te faltan {n} días con trades': '{n} more trading days needed',
  'máx.': 'max',
  'Se mide cuando tengas ganancia acumulada.': 'Measured once you have cumulative profit.',
  'Tu mejor día ({best}) es el {pct}% de la ganancia total.': 'Your best day ({best}) is {pct}% of total profit.',
  'Dentro de la regla.': 'Within the rule.',
  'Supera el máximo: necesitás más días en verde.': 'Above the max: you need more green days.',
  'Marcar como {status}': 'Mark as {status}',
  'Cargá las reglas de esta cuenta en Ajustes → Cuentas.': 'Add this account\'s rules in Settings → Accounts.',

  // ---- Onboarding ----
  'Paso 1 de 3': 'Step 1 of 3',
  'Paso 2 de 3': 'Step 2 of 3',
  'Paso 3 de 3': 'Step 3 of 3',
  '¿Cómo operás?': 'How do you trade?',
  'Así adaptamos tu journal a tu tipo de cuenta.': 'So we can tailor your journal to your account type.',
  'Trader retail': 'Retail trader',
  'Opero mi propia cuenta.': 'I trade my own account.',
  'Opero con una prop firm y tengo reglas de drawdown.': 'I trade with a prop firm and have drawdown rules.',
  'Drawdown diario (%)': 'Daily drawdown (%)',
  'Drawdown total (%)': 'Max drawdown (%)',
  'Profit target (%)': 'Profit target (%)',
  'Drawdown total': 'Max drawdown',
  'Ej. 5': 'E.g. 5',
  'Ej. 10': 'E.g. 10',
  'Ej. 8': 'E.g. 8',
  'Escribí las reglas que tiene que cumplir cada trade para ser válido. En cada operación vas a confirmar si las respetaste.': "Write the rules every trade must follow to be valid. On each trade you'll confirm whether you followed them.",
  'Mínimo 2 reglas': 'At least 2 rules',
  'Nueva regla': 'New rule',
  'Ej. Entré solo dentro de mi horario operativo': 'E.g. I only entered within my trading hours',
  'Ej. De 9:30 a 11:00 hora de Nueva York': 'E.g. From 9:30 to 11:00 New York time',
  '+ Agregar regla': '+ Add rule',
  'Todavía no agregaste reglas. Empezá por la más importante de tu estrategia.': "You haven't added any rules yet. Start with the most important one in your strategy.",
  '{n} reglas cargadas': '{n} rules added',
  '{n} de {min} reglas mínimas': '{n} of {min} minimum rules',
  'Agregá al menos {n} reglas a tu Trading Plan para seguir.': 'Add at least {n} rules to your Trading Plan to continue.',
  'Tu riesgo máximo por día': 'Your max risk per day',
  'Cuánto estás dispuesto a arriesgar como máximo en un día. Te avisamos cuando te acerques y marcamos los días en que te pasaste.': "The most you're willing to risk in a day. We'll warn you when you get close and flag the days you went over.",
  'Riesgo máximo diario (%)': 'Max daily risk (%)',
  'Ingresá un número mayor a 0 y hasta 100 (ej. 1).': 'Enter a number greater than 0 and up to 100 (e.g. 1).',
  'Revisá las reglas de tu prop firm (paso 1): tienen que ser números entre 0 y 100 (ej. 5).': 'Check your prop firm rules (step 1): they must be numbers between 0 and 100 (e.g. 5).',
  'Atrás': 'Back',
  'Siguiente': 'Next',
  'Empezar a operar': 'Start trading',

  // ---- Importador (texto fijo) ----
  'Importar trades': 'Import trades',
  'Exportá el historial de operaciones de tu plataforma como CSV y subilo acá. Todo se procesa en tu navegador.': 'Export your trade history from your platform as a CSV and upload it here. Everything is processed in your browser.',
  'Elegir archivo': 'Choose file',
  'CSV separado por comas, punto y coma o tabulaciones.': 'CSV separated by commas, semicolons or tabs.',
  'La primera fila tiene los nombres de las columnas': 'The first row has the column names',
  '¿Qué es cada columna?': 'What is each column?',
  'Elegí la columna de cada dato. Solo la fecha y el resultado son obligatorios.': 'Pick the column for each field. Only the date and the result are required.',
  'Cómo leer los datos': 'How to read the data',
  'El resultado está en': 'The result is in',
  'Dinero (USD)': 'Money (USD)',
  '% de la cuenta': '% of the account',
  'Tamaño de la cuenta (USD)': 'Account size (USD)',
  'Queda guardado en la cuenta.': 'It is saved to the account.',
  'Ej. 50000': 'E.g. 50000',
  'Formato de fecha': 'Date format',
  'Detectar solo': 'Detect automatically',
  'Día/mes/año': 'Day/month/year',
  'Mes/día/año': 'Month/day/year',
  'Año-mes-día': 'Year-month-day',
  'Las horas del archivo están en': 'Times in the file are in',
  'Hora NY': 'NY time',
  'Mi hora': 'My time',
  'UTC': 'UTC',
  'Revisá antes de importar': 'Review before importing',
  '¿Estos trades respetaron tu Trading Plan?': 'Did these trades follow your Trading Plan?',
  'Sí, todos': 'Yes, all of them',
  'Cuentan como plan seguido.': 'They count as plan followed.',
  'No, o no sé': "No, or I don't know",
  'Cuentan como plan roto hasta que los revises.': 'They count as plan broken until you review them.',
  'Quedan marcados <b>por completar</b>: editalos para sumar las reglas, la emoción, los errores y notas.': 'They are marked <b>to complete</b>: edit them to add the rules, emotion, mistakes and notes.',

  // ---- Logros ----
  'Primer paso': 'First step',
  'Registraste tu primer trade.': 'You logged your first trade.',
  'Constante': 'Consistent',
  'Registraste 10 trades.': 'You logged 10 trades.',
  'Disciplina de journal': 'Journal discipline',
  'Registraste 50 trades.': 'You logged 50 trades.',
  'Centenario': 'Centurion',
  'Registraste 100 trades.': 'You logged 100 trades.',
  'Racha de 5': 'Streak of 5',
  '5 trades seguidos respetando tu plan.': '5 trades in a row following your plan.',
  'Racha de 10': 'Streak of 10',
  '10 trades seguidos respetando tu plan.': '10 trades in a row following your plan.',
  'Racha de 25': 'Streak of 25',
  '25 trades seguidos respetando tu plan.': '25 trades in a row following your plan.',
  'Máquina': 'Machine',
  '50 trades seguidos respetando tu plan.': '50 trades in a row following your plan.',
  'Sin errores': 'Mistake-free',
  '10 trades seguidos sin marcar errores.': '10 trades in a row without logging mistakes.',
  'Semana perfecta': 'Perfect week',
  'Una semana con 3 trades o más y el plan siempre respetado.': 'A week with 3 or more trades and the plan always followed.',
  'Meta cumplida': 'Goal met',
  'Cumpliste tu meta de disciplina en un mes (con 10 trades o más y una meta de 70% o más).': 'You hit your discipline goal in a month (with 10+ trades and a goal of 70% or more).',
  'Autoconocimiento': 'Self-awareness',
  'Completaste tu primera revisión semanal.': 'You completed your first weekly review.',
  'Un mes de revisiones': 'A month of reviews',
  'Completaste 4 revisiones semanales.': 'You completed 4 weekly reviews.',
  '¡Logro desbloqueado!': 'Achievement unlocked!',
  '¡Desbloqueaste {n} logros!': 'You unlocked {n} achievements!',
  'Desbloqueado el {date}': 'Unlocked on {date}',
  'Todavía no desbloqueaste logros. El primero llega con tu primer trade.': "You haven't unlocked any achievements yet. The first one comes with your first trade.",
  'Próximo logro': 'Next achievement',
  'Ocultar': 'Hide',
  'Ver todos los logros': 'See all achievements',
  'Vas {n}/10 trades este mes': "You're at {n}/10 trades this month",
  'Vas {pct}% de {target}% de plan este mes': "You're at {pct}% of a {target}% plan goal this month",
  'Vas {cur}/{max}': "You're at {cur}/{max}",

  // ---- Inicio (contenido) ----
  'Buen día': 'Good morning',
  'Buenas tardes': 'Good afternoon',
  'Buenas noches': 'Good evening',
  'Bienvenido a tu journal. Empezá por los tres pasos de abajo.': 'Welcome to your journal. Start with the three steps below.',
  'Operá con un plan. Ejecutá con disciplina.': 'Trade with a plan. Execute with discipline.',
  'Tu compromiso de esta semana': 'Your commitment this week',
  'Regla del día · leela antes de operar': 'Rule of the day · read it before trading',
  'Armá tu Trading Plan': 'Build your Trading Plan',
  'Las reglas que tiene que cumplir cada trade.': 'The rules every trade must follow.',
  'Ir a Ajustes': 'Go to Settings',
  'Registrá tu primer trade': 'Log your first trade',
  'Resultado, plan, emoción y lo que pasó.': 'Result, plan, emotion and what happened.',
  'Hacé tu primera revisión': 'Do your first review',
  'Cinco minutos al final de la semana.': 'Five minutes at the end of the week.',
  'Ir a Revisión': 'Go to Review',
  'Primeros pasos': 'Getting started',
  '{n} de 3': '{n} of 3',
  'Racha actual': 'Current streak',
  'Mejor racha: {n}': 'Best streak: {n}',
  'Resultado semana': 'Week result',
  'Plan semana': 'Week plan',
  'Win rate semana': 'Week win rate',
  '{n} trade esta semana': '{n} trade this week',
  '{n} trades esta semana': '{n} trades this week',
  'Meta: {goal}%': 'Goal: {goal}%',
  'Superaste tu riesgo máximo ({used}% de {max}%). Hoy no operes más.': "You exceeded your max risk ({used}% of {max}%). Don't trade any more today.",
  'Llegaste a tu límite de riesgo. Hoy no operes más.': "You reached your risk limit. Don't trade any more today.",
  'Hoy rompiste el plan {n} veces. ¿Te tomás una pausa?': 'You broke your plan {n} times today. Time for a break?',
  'Rompiste el plan una vez hoy. Bajá el ritmo y revisá tus reglas antes del próximo.': 'You broke your plan once today. Slow down and review your rules before the next one.',
  'Todavía no operaste hoy. Leé tu regla del día antes de entrar.': "You haven't traded today. Read your rule of the day before entering.",
  'Vas bien: todo dentro del plan hoy.': 'Going well: everything within plan today.',
  'Trades': 'Trades',
  'En plan': 'On plan',
  'Fuera de plan': 'Off plan',
  'Riesgo usado hoy': 'Risk used today',
  'Definí tu máximo en Ajustes': 'Set your max in Settings',
  'Sin riesgo disponible': 'No risk left',
  'Te quedan <b>{n}%</b> de riesgo': 'You have <b>{n}%</b> risk left',
  'de {goal}%': 'of {goal}%',
  'Sin trades este mes': 'No trades this month',
  'Te falta 1 punto': '1 point to go',
  'Te faltan {n} puntos': '{n} points to go',
  'Trades en plan': 'Trades on plan',
  'Para llegar': 'To get there',
  '{n} seguidos en plan': '{n} in a row on plan',
  'Quedan': 'Left',
  '1 día del mes': '1 day this month',
  '{n} días del mes': '{n} days this month',
  'Rompiste el plan': 'You broke the plan',
  'Todavía no registraste trades.': "You haven't logged any trades yet.",
  'plan roto': 'plan broken',
  'Con 3 trades o más vas a empezar a ver patrones de tu operativa acá.': "With 3 or more trades you'll start seeing patterns in your trading here.",
  'Todavía no hay patrones claros. Seguí registrando emociones y errores en cada trade.': 'No clear patterns yet. Keep logging emotions and mistakes on every trade.',
  'Trade {n}': 'Trade {n}',
  'Con tu plan': 'With your plan',
  'Registrá al menos un trade para ver tu curva.': 'Log at least one trade to see your curve.',

  // ---- Patrones automáticos ----
  'Lun': 'Mon',
  'Mar': 'Tue',
  'Mié': 'Wed',
  'Jue': 'Thu',
  'Vie': 'Fri',
  'Sáb': 'Sat',
  'Dom': 'Sun',
  'lunes': 'Mondays',
  'martes': 'Tuesdays',
  'miércoles': 'Wednesdays',
  'jueves': 'Thursdays',
  'viernes': 'Fridays',
  'sábados': 'Saturdays',
  'domingos': 'Sundays',
  'Después de una pérdida rompés el plan el <b>{a}</b> de las veces (contra {b} el resto). Ojo con la revancha.': 'After a loss you break your plan <b>{a}</b> of the time (vs. {b} otherwise). Watch out for revenge trading.',
  'Después de una pérdida mantenés la cabeza fría: rompés el plan solo el {a} de las veces.': 'After a loss you keep a cool head: you break your plan only {a} of the time.',
  'Cuando seguís tu plan promediás <b>{f}</b> por trade; cuando lo rompés, <b>{b}</b>.': 'When you follow your plan you average <b>{f}</b> per trade; when you break it, <b>{b}</b>.',
  'Romper el plan ya te costó <b>{sum}</b> en total ({n} trades).': 'Breaking your plan has already cost you <b>{sum}</b> in total ({n} trades).',
  'Tus trades con <b>{emo}</b> promedian <b>{avg}</b> ({n} trades).': 'Your trades while <b>{emo}</b> average <b>{avg}</b> ({n} trades).',
  'Operando <b>{emo}</b> promediás <b>{avg}</b> por trade.': 'Trading <b>{emo}</b> you average <b>{avg}</b> per trade.',
  'Tus trades con <b>{emo}</b> promedian <b>{avg}</b>.': 'Your trades while <b>{emo}</b> average <b>{avg}</b>.',
  'Tu error más repetido es <b>"{err}"</b>: {n} veces, con un resultado promedio de <b>{avg}</b>.': 'Your most repeated mistake is <b>"{err}"</b>: {n} times, with an average result of <b>{avg}</b>.',
  'Tu mejor sesión es <b>{s}</b>: promediás {avg} por trade.': 'Your best session is <b>{s}</b>: you average {avg} per trade.',
  'Tu mejor horario es de <b>{from}:00 a {to}:00</b> hora NY ({avg} por trade).': 'Your best hour is <b>{from}:00 to {to}:00</b> NY time ({avg} per trade).',
  'Entre las {from}:00 y las {to}:00 (hora NY) seguís tu plan solo el {pct} de las veces.': 'Between {from}:00 and {to}:00 (NY time) you follow your plan only {pct} of the time.',
  'Los <b>{day}</b> es cuando más rompés el plan (lo seguís el {pct} de las veces).': '<b>{day}</b> are when you break your plan the most (you follow it {pct} of the time).',
  'Tu intuición funciona: con confianza alta promediás {hi}, con confianza baja {lo}.': 'Your intuition works: with high confidence you average {hi}, with low confidence {lo}.',
  'Cuidado con el exceso de confianza: con confianza alta promediás {hi}, menos que con confianza baja ({lo}).': 'Watch out for overconfidence: with high confidence you average {hi}, less than with low confidence ({lo}).',
  'Te va mejor en <b>{a}</b> ({avgA} por trade) que en {b} ({avgB}).': 'You do better on <b>{a}</b> ({avgA} per trade) than on {b} ({avgB}).',
  'En tus ganadores planeás 1:{planned} pero cobrás {real}R en promedio: estás cerrando antes de tiempo.': "On your winners you plan 1:{planned} but take {real}R on average: you're closing too early.",

  // ---- Estadísticas (contenido) ----
  'Últimos 3 meses': 'Last 3 months',
  'Todo tu historial': 'Your full history',
  'semana pasada': 'last week',
  'mes pasado': 'last month',
  '3 meses anteriores': 'previous 3 months',
  'Todo el historial': 'Full history',
  'Sin período anterior': 'No previous period',
  '= que {label}': 'same as {label}',
  'pts': 'pts',
  '{txt} vs {label}': '{txt} vs {label}',
  'período anterior': 'previous period',
  'Resultado acumulado': 'Cumulative result',
  'Siguió el plan': 'Followed the plan',
  'Win rate': 'Win rate',
  'Resultado prom./trade': 'Avg result/trade',
  'Riesgo promedio': 'Avg risk',
  'Duración promedio': 'Avg duration',
  'R real promedio': 'Avg actual R',
  'plan respetado': 'plan followed',
  'Registrá trades para medir tu disciplina.': 'Log trades to measure your discipline.',
  'Estás arriba de tu meta del {goal}%': "You're above your {goal}% goal",
  'Te faltan {n} pts para tu meta del {goal}%': "You're {n} pts away from your {goal}% goal",
  'trades en plan': 'trades on plan',
  'racha actual': 'current streak',
  'mejor racha': 'best streak',
  'Romper el plan te costó {n} puntos': 'Breaking your plan cost you {n} points',
  'Resultado real {real} · con tu plan habrías hecho {plan}.': 'Actual result {real} · with your plan you would have made {plan}.',
  'Respetaste tu plan en todos los trades': 'You followed your plan on every trade',
  'Resultado del período: {real}. Así se construye un sistema medible.': "Period result: {real}. That's how you build a measurable system.",
  'Con 3 trades o más en el período vas a empezar a ver patrones.': "With 3 or more trades in the period you'll start seeing patterns.",
  'Todavía no hay patrones claros. Registrá emoción, errores, activo y horario en cada trade: cuantos más datos, más patrones aparecen.': 'No clear patterns yet. Log emotion, mistakes, asset and time on every trade: the more data, the more patterns show up.',
  'Lo que te funciona': 'What works for you',
  'Todavía no aparece un patrón positivo claro.': 'No clear positive pattern yet.',
  'Lo que te cuesta plata': 'What costs you money',
  'No aparecen patrones que te estén costando.': 'No patterns costing you money.',
  'Para tener en cuenta': 'Worth noting',
  'Registrá trades con su hora de entrada para ver el mapa.': 'Log trades with their entry time to see the map.',
  '{from}:00 a {to}:00 NY': '{from}:00 to {to}:00 NY',
  'Marcá cómo te sentías al entrar en cada trade para ver este desglose.': 'Log how you felt when entering each trade to see this breakdown.',
  'Error': 'Mistake',
  'Todavía no marcaste errores en tus trades.': "You haven't logged mistakes on your trades yet.",
  'Cargá el activo en tus trades para ver este desglose.': 'Add the asset to your trades to see this breakdown.',
  'Cargá el setup en tus trades para ver este desglose.': 'Add the setup to your trades to see this breakdown.',
  'Marcá si fue long o short para ver este desglose.': 'Mark whether it was long or short to see this breakdown.',
  'Prom./trade': 'Avg/trade',
  'Total': 'Total',
  'Todavía no hay datos.': 'No data yet.',
  'Mejor': 'Best',
  'Peor': 'Worst',
  'Todavía no hay trades en el período.': 'No trades in this period yet.',
  'Duración': 'Duration',
  'Acumulado': 'Cumulative',
  'Armá tu Trading Plan en Ajustes para ver qué reglas cumplís más.': 'Build your Trading Plan in Settings to see which rules you follow most.',
  'Tus reglas actuales son más nuevas que los trades del período.': 'Your current rules are newer than the trades in this period.',
  'Meta no cumplida': 'Goal not met',
  '<b>{n}</b> trades': '<b>{n}</b> trades',
  '<b>{n}</b> por día operado': '<b>{n}</b> per trading day',
  '<b>{n}</b> risk mgmt': '<b>{n}</b> risk mgmt',

  // ---- Calendario ----
  'No registraste trades en {period}.': 'You did not log trades in {period}.',
  '{g} verdes · {r} rojos': '{g} green · {r} red',
  'Mejor día': 'Best day',
  'Peor día': 'Worst day',
  'Días en verde': 'Green days',
  'Días seguidos en verde': 'Green days in a row',
  '1 día': '1 day',
  '{n} días': '{n} days',
  'Semana': 'Week',
  '{n}% plan': '{n}% plan',
  'Sin trades': 'No trades',
  'Mejor mes': 'Best month',
  'Peor mes': 'Worst month',
  'Meses en verde': 'Green months',
  '{n} de {total}': '{n} of {total}',
  'Meses con trades': 'Months with trades',
  'Plan siempre seguido': 'Plan always followed',
  'A veces roto': 'Sometimes broken',
  'Siempre roto': 'Always broken',
  'Trade con plan seguido': 'Trade with plan followed',
  'Pérdida': 'Loss',
  'Ganancia': 'Profit',
  'No registraste trades este día.': "You didn't log trades on this day.",
  'R total': 'Total R',
  'Faltó del plan: {rules}': 'Missed from plan: {rules}',
  'Ver detalle': 'See details',

  // ---- Historial ----
  'Trades filtrados': 'Filtered trades',
  'Limpiar filtros': 'Clear filters',
  '{n} por completar': '{n} to complete',
  'Importar CSV': 'Import CSV',
  'Exportar CSV': 'Export CSV',
  'Riesgo {n}%': 'Risk {n}%',
  '{n} fuera de plan': '{n} off plan',
  'Ningún trade coincide con los filtros': 'No trades match the filters',
  'Probá con otra búsqueda o sacá algún filtro.': 'Try another search or remove a filter.',
  'Todavía no registraste ningún trade': "You haven't logged any trades yet",
  'Cada trade que cargues aparece acá con su resultado, tu plan, tu emoción y tus notas.': 'Every trade you log shows up here with its result, your plan, your emotion and your notes.',
  'Mostrando {n} de {total}': 'Showing {n} of {total}',
  'Cargar más': 'Load more',
  'Mostrando los {n} trades': 'Showing all {n} trades',
  '(regla que ya no está en tu plan)': '(rule no longer in your plan)',
  'Riesgo': 'Risk',
  'Importado · por completar': 'Imported · to complete',
  'Disciplina {n}/100': 'Discipline {n}/100',
  'Risk management roto ese día': 'Risk management broken that day',
  'Seguido': 'Followed',
  'Roto': 'Broken',
  'No tenías reglas cargadas.': "You didn't have any rules set.",
  'Confianza': 'Confidence',
  'Sin errores marcados.': 'No mistakes logged.',
  'Qué pasó en el trade': 'What happened in the trade',
  'Sin comentarios.': 'No comments.',
  '¿Eliminar este trade? No se puede deshacer.': 'Delete this trade? This cannot be undone.',
  'Fecha': 'Date',
  'Hora': 'Time',
  'Hora (NY)': 'Time (NY)',
  'Resultado %': 'Result %',
  'Riesgo %': 'Risk %',
  'Duración (min)': 'Duration (min)',
  'Reglas que faltaron': 'Missed rules',
  'Nota': 'Note',

  // ---- Revisión ----
  'Excelente': 'Excellent',
  'Sólida': 'Solid',
  'Regular': 'Fair',
  'Floja': 'Weak',
  'Semana pasada': 'Last week',
  'Revisada': 'Reviewed',
  'Pendiente': 'Pending',
  '1 semana revisada': '1 week reviewed',
  '{n} semanas seguidas revisando': '{n} weeks in a row reviewing',
  'Tu compromiso para esta semana': 'Your commitment for this week',
  'Sin semana previa para comparar': 'No previous week to compare',
  '= que la semana pasada': 'same as last week',
  '{txt} vs semana pasada': '{txt} vs last week',
  '{n} la semana pasada': '{n} last week',
  'Meta {goal}%': 'Goal {goal}%',
  'sin trades': 'no trades',
  'No registraste trades esta semana.': "You didn't log trades this week.",
  'Error más repetido': 'Most repeated mistake',
  '1 vez': 'once',
  '{n} veces': '{n} times',
  '<b>No marcaste errores</b> esta semana': '<b>No mistakes logged</b> this week',
  'Emoción más frecuente': 'Most frequent emotion',
  '{avg} promedio': '{avg} average',
  '<b>1 trade</b> fuera de plan · sumó {sum}': '<b>1 trade</b> off plan · totaling {sum}',
  '<b>{n} trades</b> fuera de plan · sumaron {sum}': '<b>{n} trades</b> off plan · totaling {sum}',
  'Plan': 'Plan',
  '<b>Respetaste tu plan</b> en todos los trades': '<b>You followed your plan</b> on every trade',
  'en {asset}': 'on {asset}',
  'Mejor y peor trade': 'Best and worst trade',
  'Ver el trade de la semana': "See this week's trade",
  'Ver los {n} trades de la semana': "See this week's {n} trades",
  'Actualizar revisión': 'Update review',
  'Tenés cambios sin guardar en esta semana.': 'You have unsaved changes for this week.',
  'Guardada el {date}': 'Saved on {date}',
  '{n} de 10': '{n} of 10',
  'Nota de disciplina': 'Discipline score',
  'Promedio <b>{n}</b>': 'Average <b>{n}</b>',
  'Todavía no hiciste ninguna revisión': "You haven't done any reviews yet",
  'Respondé las tres preguntas y calificá tu semana. Te lleva cinco minutos y es donde más se aprende.': "Answer the three questions and rate your week. It takes five minutes and it's where you learn the most.",
  'Desbloquea el logro "Autoconocimiento"': 'Unlocks the "Self-awareness" achievement',
  'Es momento de revisar tu semana': "It's time to review your week",
  '1 trade sin revisar. Te lleva cinco minutos.': '1 trade to review. It takes five minutes.',
  '{n} trades sin revisar. Te lleva cinco minutos.': '{n} trades to review. It takes five minutes.',
  'Revisar ahora': 'Review now',
  'Respondé al menos una pregunta para guardar la revisión.': 'Answer at least one question to save the review.',
  'Revisión guardada.': 'Review saved.',

  // ---- Importador (contenido) ----
  'Hora de entrada (si viene en otra columna)': 'Entry time (if in a separate column)',
  'Fecha y hora de salida (para la duración)': 'Exit date and time (for duration)',
  'Dirección (compra / venta)': 'Direction (buy / sell)',
  'Comisiones (se restan del resultado)': 'Fees (subtracted from the result)',
  'Columna {n}': 'Column {n}',
  'no se entiende la fecha "{v}"': 'the date "{v}" is not recognized',
  'la fecha es futura': 'the date is in the future',
  'el resultado "{v}" no es un número': 'the result "{v}" is not a number',
  'falta el tamaño de la cuenta': 'the account size is missing',
  'el resultado da {n}%: revisá el tamaño de la cuenta o la columna': 'the result comes out to {n}%: check the account size or the column',
  'Revisar': 'Review',
  'Detectado: {fmt}.': 'Detected: {fmt}.',
  'año-mes-día': 'year-month-day',
  'día/mes/año': 'day/month/year',
  'mes/día/año': 'month/day/year',
  'No se puede saber si es día/mes o mes/día (ningún día pasa de 12). Se usa día/mes/año: elegilo a mano si tu archivo es mes/día.': "Can't tell whether it's day/month or month/day (no day is above 12). Using day/month/year: pick it manually if your file is month/day.",
  'El resultado ya está en % de la cuenta.': 'The result is already in % of the account.',
  'Se pasa a % con el tamaño de "{acc}": {size}.': 'Converted to % using the size of "{acc}": {size}.',
  'Para pasarlo a % hace falta el tamaño de la cuenta.': 'The account size is needed to convert it to %.',
  'trade nuevo': 'new trade',
  'trades nuevos': 'new trades',
  'fila con error': 'row with errors',
  'filas con error': 'rows with errors',
  'Fila {n}: {msg}': 'Row {n}: {msg}',
  '…y {n} más.': '…and {n} more.',
  'y {n} más': 'and {n} more',
  '1 fila': '1 row',
  '{n} filas': '{n} rows',
  'Importar': 'Import',
  'Importar 1 trade': 'Import 1 trade',
  'Importar {n} trades': 'Import {n} trades',
  '1 trade importado': '1 trade imported',
  '{n} trades importados': '{n} trades imported',
  'El archivo es muy grande (máximo 5 MB).': 'The file is too large (max 5 MB).',
  'No se encontraron columnas. Exportá el historial como CSV (separado por comas o punto y coma).': 'No columns found. Export your history as CSV (separated by commas or semicolons).',
  'Elegí la columna de la fecha de entrada.': 'Pick the entry date column.',
  'Elegí la columna del resultado.': 'Pick the result column.',
  'Ingresá el tamaño de la cuenta en USD (ej. 50000) para pasar el resultado a %.': 'Enter the account size in USD (e.g. 50000) to convert the result to %.',
  'Elegí si estos trades respetaron tu Trading Plan.': 'Choose whether these trades followed your Trading Plan.',
  'No se pudo guardar: el almacenamiento del navegador está lleno.': "Couldn't save: browser storage is full.",
  'Quedan "por completar": sumales emoción, errores y notas.': 'They are marked "to complete": add emotion, mistakes and notes.',

  // ---- Backup ----
  'El archivo no es un backup válido (no se pudo leer).': "The file isn't a valid backup (it couldn't be read).",
  'El archivo no parece un backup del journal.': "The file doesn't look like a journal backup.",
  'El backup es de una versión más nueva de la app.': 'The backup is from a newer version of the app.',
};
